use Unicode::Normalize 'normalize';
use utf8;

$c->{reading_text_stop_words_list} = [
"defferrés","deuotemet","puisqu'il",
"mescheance","mescheans","mescheanz","meschief","mescreance",
"qu'an",

"0","a","ab","ac","aclergis","ad","adiuua","adons","adorant","adrez",
"aduocatrix","agamus","age","agnus","ai","aie","aient","aies","aiez","aiiés",
"aijés","aillors","aillours","aincor","ait","aié","aiés","al","allors","allours",
"almus","am","amabilis","amone","amoris","amploiee","an","ancor","ancores","anfor",
"angeles","angelis","angelorum","aniex","anploiee","aperit","aprés","ar","ara","arai",
"ardoir","arez","argent","ariere","arieres","aroi","aroie","aroit","aroye","ars",
"artium","arés","as","asouueÿr","asprement","asprete","asralié","asseis","assez","asés",
"at","atalente","atraiance","atraire","atrium","au","aual","auan","auance","auant",
"auc","aucuns","audi","aue","auec","aueir","aueiz","aueoir","aueques","auerai",
"aueroie","aueuc","aueucke","auez","aul","auoc","auoec","auoie","auoir","auoit",
"aura","aurai","auray","aurei","aureis","aurez","auroi","auroie","auroiz","aurons",
"aurés","aus","ausi","ausint","aussi","aut","autant","autem","autre","autrement",
"autres","autresi","autrui","auuec","auugle","aux","aué","aués","av","avantaige",
"ave","avecques","averai","aver","aveuc","aveuckes","aveugle","avez","avoec","avoeques",
"avoir","avé","avés","ay","ayt","b","bait","barat","bas","beatis",
"bec","bee","bei","beit","benedicamus","bet","bethlehem","bien","bin","bis",
"biuonetz","bjen","bobance","bonas","boqe","bordon","boucher","bouchier","bouqe","brauium",
"brief","briez","bruit","buef","buer","bure","c","c'a","c'ai","c'ains",
"c'ainz","c'an","c'apeirt","c'au","c'aurai","c'autre","c'autrement","c'autres","c'ele","c'elle",
"c'en","c'es","c'est","c'il","c'om","c'on","c'oncore","c'onqes","c'onques","c'or",
"c'ore","c'un","c'une","cai","can","canque","capit","car","carcere","caritas",
"carne","carneam","castitas","ce","cel","cele","celebrem","celestium","celi","celicum",
"celle","cellui","celluy","celly","cels","celui","cembel","ceo","cera","cert",
"certaine","certeine","certeinement","certes","ces","cest","ceste","cetera","ceu","cha",
"chaciés","chainse","chaloir","chamin","char","chasteé","chat","che","chele","cheli",
"cher","chest","cheste","chi","chien","chier","chiere","chil","chix","chou",
"ci","cil","cilz","cis","cist","cité","ciuiere","cius","ciz","cjs",
"cloroit","clorroit","cognissance","cognitas","cognoist","coi","coins","colee","com","combat",
"come","coment","comme","comment","commere","comprendre","comun","con","conferme","confermet",
"confert","confertur","confonde","conme","conment","connoist","conoist","conplainte","conroi","consaut",
"conseil","conseilliés","consent","conseut","consirer","consoit","conte","contraire","contratendant","contre",
"conuertentem","copia","corde","cordibus","cordis","cornettes","corrouz","cort","couant","couchai",
"couchier","coudroie","couille","coulle","coument","counoist","coup","coupe","couppe","courroucier",
"courrucié","courte","cousu","couuerture","coux","cras","creature","crere","crescens","crigne",
"crine","crinne","croissent","croix","crollet","cruce","cu","cude","cui","cul",
"cullir","cum","cur","cure","currencium","cy","d'a","d'ambedeux","d'ame","d'anbedeux",
"d'argent","d'arme","d'armes","d'assez","d'assés","d'atrui","d'auenir","d'aultrui","d'auoir","d'aus",
"d'autel","d'autre","d'autretel","d'autrui","d'avoir","d'awan","d'elegier","d'enfern","d'eschiueir","d'estre",
"d'esté","d'ire","d'ortie","d'ou","d'outre","d'outremer","d'un","d'une","d'vn","da",
"dahait","dahez","dains","dairt","dam","damnés","dampnés","dan","dant","danz",
"dar","dart","das","dat","datis","datur","de","dearragié","debitas","dechaciés",
"decus","dedaignouze","dedens","dedit","defaus","defaut","defaute","defera","defferés","deffie",
"defrit","degraz","degré","dehait","dehaiz","dei","deificum","del","delaie","deleuit",
"demie","denié","dens","dent","denz","deo","deprecare","deques","derora","des",
"desere","desfie","desfié","deshait","desloie","desous","desouz","despansans","despeit","despice",
"despit","desproué","dessouz","dessus","destinee","destiné","destoupeit","destresse","destroit","desuestus",
"desus","desvestus","detre","detri","deuant","deuis","deuise","deuize","deum","deuorés",
"deuotement","deuotemt","deuoto","devise","dez","dicite","dictas","dictes","die","digna",
"diversent","doble","dobleir","dobler","doblera","doces","doctrine","domine","domino","donc",
"doncques","donques","dongier","dongiers","dons","dont","dor","dotain","dotance","dou",
"doubler","doublera","dout","doutance","doute","draps","drincheyl","du","duc","duce",
"dulcissima","dune","dunt","dusqu'a","dusques","dux","d'aultrui","d'avoir","d'elegier","d'estre",
"e","ea","eage","eai","eaige","eclesie","eest","eeue","egypte","ei",
"einsi","einsin","einsint","einssi","eis","eit","el","ele","eles","elle",
"elles","ellire","emanuel","embrace","empetrez","emprendre","emprent","emprisonés","en","encliné",
"encontre","encor","encore","encores","encousue","endroit","enfuie","enganez","enganés","engignié",
"enhaï","enla","enmuree","enploiee","enragie","enrichis","enrragiez","ens","enseueli","ensi",
"ensient","enssi","ent","ente","entient","entier","entiere","entieremant","entire","entre",
"entremectre","entremettre","entsi","enuaï","enuers","eos","ere","eripit","erré","errés",
"ert","es","escheuie","eschiuee","escient","escorchier","escïent","eslaceer","eslire","esmai",
"esmerueille","esploit","esploita","espousera","espuee","espé","esragie","essin","est","estable",
"estaindre","estei","esteis","ester","estes","estient","estincele","estoet","estoit","estre",
"esté","et","eu","euc","euch","eue","eve","ex","exenplario","exilio",
"exordium","extremitas","ez","eü","eür","eüsse","fa","fac","face","facent",
"fach","fache","faciez","faciés","facta","faet","fai","faic","faice","faictes",
"faire","fais","faisans","fait","faite","faites","faiz","fareis","fas","fascia",
"fate","fault","fay","faz","façon","fecunda","feire","feit","fer","fera",
"ferai","ferait","ferat","feray","fere","fereis","ferez","feriés","feroie","ferois",
"feroit","ferons","feront","ferret","feruida","ferunt","feré","fes","fet","fetes",
"feur","feïs","feïsse","feïst","fiance","fichera","ficherai","fide","fie","fiel",
"fier","fierete","fiez","figat","figit","figure","fil","filer","filg","filio",
"filium","fis","fist","fit","fius","foire","fois","foix","fonde","fons",
"font","for","force","forche","forestier","forfet","formant","forment","fors","fort",
"fos","foue","foule","fourestier","fourfaisans","fourré","fours","françois","frese","frestele",
"frigandés","froiches","fruens","fu","fuer","fui","fuians","fuiez","fuison","fuissent",
"fuissiés","fuisti","fuit","fuiés","fus","fuse","fusiez","fusse","fussent","fussiez",
"fussiés","fust","fut","futurum","fuy","fycherai","g","g'en","g'ere","g'i",
"g'ier","g'iere","g'ié","g'é","gaaigneroit","gaber","gabriel","gaigneroit","gaillarde","gaires",
"gairt","gaite","gaitent","gaiteurs","game","garni","gars","gart","gas","gastee",
"gaterés","gaudia","gaudium","gauz","ge","gedeonis","gehir","gemina","gemineo","genitoris",
"genitrix","genous","genoz","germani","geronnees","ges","geter","geu","giganti","gillette",
"girodele","girondele","gironees","gironnees","gitez","glacier","glai","glaiolais","gloire","gloria",
"glorie","glorificum","gloriosa","gorpiz","goustez","goustés","goy","graci","gracias","graile",
"grain","grano","granum","gras","guas","gueires","gueiteurs","guere","guerre","guerroie",
"guerroier","guete","guise","guisse","gute","ha","habet","habitas","hachie","haire",
"halete","hallee","han","hardi","hart","has","haschie","haste","hastis","hastés",
"hellequin","hemne","herbages","herbaige","hi","ho","hoc","hodie","hokes","hominem",
"hors","hostia","hous","housiaus","houx","houziaus","hoziaus","humés","hure","hurta",
"i","i'a","i'abaterai","i'ai","i'aie","i'an","i'arai","i'auerai","i'auoie","i'aurai",
"i'avoir","i'ay","i'ei","i'en","i'ere","i'estoie","i'é","ia","iai","iaus",
"icel","icele","icels","icest","ichi","ici","icy","id","ie","iehir",
"iel","ier","iere","iert","ierusalem","iestes","iestre","igne","ignem","igni",
"il","illi","illuminans","im","immolatus","in","induco","induit","ine","inficiunt",
"io","iou","iouster","ioute","ire","israhel","issi","istra","istre","iu",
"iubilo","iudaice","iugement","iui","iuijs","ius","iusque","iusques","iustise","iustum",
"j","j'a","j'ai","j'aie","j'an","j'arai","j'aurai","j'ay","j'aye","j'en",
"j'ere","j'ey","ja","jai","jairt","jangleos","janglerie","jardinet","jay","je",
"jen","jeo","jl","jo","jou","jre","ju","jugement","jus","jusques",
"jv","k'a","k'ainc","k'ains","k'ainz","k'an","k'assés","k'au","k'auoc","k'auoie",
"k'autre","k'autres","k'autresi","k'ele","k'elle","k'elles","k'en","k'ensi","k'il","kai",
"kan","kank'il","kant","kar","ke","keil","kerre","kes","ki","kiconques",
"koi","l","l'a","l'abe","l'ai","l'aie","l'ait","l'ame","l'an","l'ante",
"l'arai","l'arbre","l'aube","l'auera","l'auiés","l'auoir","l'auoit","l'aura","l'aurai","l'auray",
"l'auré","l'autre","l'autrier","l'aviés","l'avoir","l'avoirs","l'ay","l'eez","l'eglise","l'eglyse",
"l'en","l'escot","l'est","l'eue","l'i","l'oliuier","l'om","l'on","l'ore","l'ot",
"l'uns","l'é","la","laborer","lace","lai","laice","laide","laisette","lance",
"lanche","larges","larmes","laron","larron","larrons","las","lasse","lassete","lassette",
"latuit","laudare","laudor","laus","le","leis","lente","lepra","lermer","lermes",
"les","lesçun","leticia","leticie","leuchet","leui","leur","lex","lez","li",
"lie","ligaf","ligat","liges","ligier","lille","lire","lis","lit","liura",
"liurés","liz","lj","locum","logemt","loire","loiriete","loirion","loisir","lor",
"lors","losangier","losenger","losengier","lou","lour","lucis","lui","luist","lundi",
"lupinele","ly","lés","m","m'a","m'afebloie","m'aie","m'aigrie","m'ais","m'ait",
"m'ame","m'amistié","m'an","m'ara","m'arés","m'asseür","m'at","m'atalent","m'atalente","m'aueis",
"m'auez","m'auoit","m'aura","m'aurait","m'aureis","m'aués","m'aveis","m'avez","m'avés","m'en",
"m'enbelist","m'ent","m'entente","m'ert","m'esmai","m'esprent","m'est","m'ester","m'estes","m'eut",
"m'i","m'iert","m'on","m'ont","m'ot","m'out","m'y","ma","magrei","mai",
"maig","maintenant","mainz","maire","mais","maisele","maison","maissele","maistrie","maix",
"maiz","malauisés","malgrei","malgré","malle","malmenant","malois","maloit","malparliere","maltalent",
"malum","manche","manes","manie","manierette","manoir","mar","mare","maria","marrit",
"mars","martire","marz","mas","mater","matons","maudahait","maudehait","maugré","mautalent",
"mauvoir","may","me","mehaigne","mei","meilleur","meillor","meillors","meillour","meillours",
"meint","melius","melz","memes","men","mençoigne","mer","meri","merita","merri",
"meruail","meruaille","mes","mesauenir","meschant","mescine","meserrez","mesire","mespensans","messire",
"mestre","mestres","mestrie","meuz","mey","meyre","mez","mi","miaus","miauz",
"mie","miels","mielz","mien","miens","mies","mieudre","mieulx","mieus","mieux",
"mieuz","miex","miez","millor","millour","millours","mins","miols","mire","miserie",
"mitis","mius","mix","mocke","moi","moie","moies","moins","mois","moitié",
"moke","mokiés","moles","molt","mon","monter","moquez","moquiés","moribus","morrie",
"mortificata","morum","moult","mout","moy","mu","muciez","muciés","mue","muedre",
"muels","muelz","muere","mues","muez","muguet","mulier","mulierum","mult","mun",
"mundane","mundi","mundoque","mundum","mus","my","mé","més","n","n'a",
"n'ai","n'aie","n'ait","n'aiés","n'an","n'aproche","n'aprochiez","n'ara","n'aroie","n'aroit",
"n'assentez","n'at","n'auarat","n'auera","n'auerai","n'aueroie","n'auez","n'aura","n'aurai","n'aurait",
"n'auray","n'aurez","n'auriez","n'auroie","n'auroit","n'aurés","n'aués","n'ay","n'ayt","n'ele",
"n'elle","n'em","n'en","n'encor","n'enport","n'enquore","n'ensaiera","n'ent","n'ere","n'ert",
"n'es","n'est","n'et","n'eut","n'ey","n'eüxe","n'i","n'iere","n'iert","n'istrai",
"n'o","n'oi","n'oncor","n'onkes","n'onques","n'ont","n'ot","n'uevre","n'unques","n'y",
"n'yerent","n'é","na","nacio","naie","naist","nam","nanil","natio","nature",
"natus","ne","neant","nee","neient","neiz","nel","nenil","nennil","neporcant",
"nes","nete","neu","ni","niant","nient","nil","nimphe","nis","nit",
"nititur","no","nobilitas","nobis","noiant","noient","noire","nois","nomen","non",
"nonpor","nonporcant","nos","nostra","nostre","nostris","nou","nous","noz","noël",
"nube","nuc","nue","nuef","nul","nule","nullam","nulle","nullui","nuls",
"nului","nulz","nunc","nuncius","nuns","nunz","nus","nuz","nuzlui","nvs",
"néo","o","oan","od","oi","oltree","om","omnis","omnium","on",
"onan","oncor","oncore","oncques","onkes","onqe","onqes","onques","onquez","onquor",
"ont","operis","or","ora","orandroit","ordenez","ordenés","ordines","ore","orendroit",
"ores","ori","oris","ornata","ortie","ortus","ot","ou","ouec","ourlé",
"out","outrageus","outre","outree","outreement","ouurier","ov","oé","p","pa",
"pace","paee","paie","paiera","pain","pais","palerin","papelart","par","parem",
"parfais","parfaite","parfaitement","parfete","paris","parix","parmi","pas","pater","patri",
"patrie","patrium","patruum","peccati","peccatum","pecche","pechié","pecunia","peir","peires",
"pelerim","pelerin","peliçon","per","perceus","pere","peril","pernez","perpetuo","perpetuum",
"personis","pessue","pestri","pestris","peu","peux","pex","pez","pia","piau",
"pickenpot","pickentpot","pieau","piecea","pieu","pieux","pieça","piis","pikempot","plai",
"plaie","pikenpot","pinkenpot","piour","pire","pis","pié","piés","plaie","plano",
"plevis","pluie","plus","plust","plux","pluz","po","poinnes","pointure","poise",
"poissance","poissans","poitrine","poize","pol","ponce","por","porcant","porchier","porqant",
"possimus","pou","pouc","poul","pour","pourquoy","poursieuroit","poursuiuroit","poynt","praelet",
"pramesse","precum","prelaz","pres","presidium","pressuris","prestat","pretancium","preuost","prevoust",
"prez","pries","prima","primez","principaument","priué","priveté","pro","prodest","proesce",
"proesse","prou","prouidence","pu","puce","pues","puis","pusqu'il","puisque","pur",
"pure","put","pvis","q'a","q'ai","q'an","q'au","q'autre","q'autresi","q'en",
"q'il","q'om","q'un","qanqe","qanqu'il","qanque","qant","qar","qe","qel",
"qi","qoi","qu'a","qu'adés","qu'ai","qu'aie","qu'ainc","qu'assez","qu'au","qu'auerai",
"qu'auoie","qu'auoir","qu'aurai","qu'ausi","qu'autre","qu'avons","qu'ay","qu'aye","qu'el","qu'ele",
"qu'eles","qu'elle","qu'en","qu'entre","qu'est","qu'ieu","qu'il","qu'oi","qu'or","quam",
"quan","quand","quanqe","quanque","quanques","quant","quar","quasser","que","quel",
"quellir","quem","quens","queque","queris","queus","queux","quex","qui","quiconques",
"quil","quin","quit","quo","quoi","quoquillete","quoy","qvant","qve","qvel",
"qvi","r","rai","raist","ranfuzeit","rape","rauerai","raui","rauoit","raurai",
"reatus","rechoit","reclamer","recoumandons","redimes","redimitas","redout","redoute","refais","regina",
"regna","regnare","regnat","regnum","regretot","releuauit","relicta","reliqum","reluisoit","remedium",
"remontés","remue","remuer","remué","renardie","reniast","renoie","repaire","reperitur","requie",
"resort","resours","resourz","respice","respit","respuns","restituitur","retaudrai","retour","retraire",
"reuel","reuerdir","reuertatur","reuiendo","rex","reçoit","rien","riens","rienz","riredure",
"riuaige","rius","robe","rogamus","roi","rois","roissoles","romanz","ronc","rosine",
"rous","roy","rue","s'a","s'ai","s'ainkes","s'ainques","s'aipert","s'alme","s'alongera",
"s'ame","s'an","s'apert","s'arai","s'aucun","s'auerons","s'auilenist","s'auilonist","s'aura","s'aurai",
"s'auray","s'aureis","s'auriés","s'auroiz","s'aurés","s'autrement","s'avrai","s'ay","s'el","s'ele",
"s'elle","s'en","s'enfuie","s'ensi","s'entente","s'est","s'i","s'iere","s'iert","s'il",
"s'on","s'onkes","s'onques","sa","sacrario","sacrificata","salua","saluari","salutis","san",
"sanctorum","sanguine","sans","santé","sanz","saous","sarasin","sarrasin","sarrazin","sautele",
"scitis","se","seant","seculo","seculum","sed","seez","sei","seli","sella",
"selonc","semer","seminans","semont","senee","sensilis","sentele","sepmaines","sequere","sera",
"serai","seray","seri","seroi","seroie","seroit","serray","seré","ses","seu",
"seue","seur","seure","seus","seux","sez","seürement","seürté","si","sicles",
"siecle","siecles","siegle","sien","siens","sienz","siet","silz","sine","sis",
"sit","sith","soc","soeif","soi","soie","soient","soiez","soir","soit",
"soiés","sol","soliers","som","sommes","son","sonerait","sont","sor","sou",
"souant","soue","soueif","souent","souerain","sougis","souhaidier","souine","soupe","souppe",
"sour","sourt","sous","souuent","souz","soweif","soweit","soy","soz","speciosa",
"speculum","spem","spes","stadium","stola","su","sua","subsidia","sue","suer",
"suffragia","sui","suis","suix","suiz","sun","sunamitis","sunt","suos","super",
"supplicancium","sur","surgens","sus","suy","suz","sy","synaï","t","t'ai",
"t'en","t'est","ta","tabair","tabairt","tabar","tailler","taillier","tair","tairt",
"taisir","tal","talant","talens","talent","tamprement","tannt","tanrement","tant","taprement",
"tarza","taunt","taut","te","tedium","teil","teile","teille","teire","tel",
"tele","teles","telle","teltes","telz","temprement","tendo","tenebris","teritur","termes",
"termino","tes","teu","teus","tey","tez","thronis","tier","tieux","tiex",
"tir","toi","ton","tor","tormentis","tors","tort","torta","tos","tost",
"tostans","tot","tote","totz","toudis","touiours","toujours","tour","touriours","tours",
"tous","tout","toute","toutes","touz","toz","trabeam","trace","trage","trahat",
"tramiti","trepe","tres","trestous","trestout","trestoute","trestoz","trestuit","tretous","trez",
"tribua","tribus","trino","trinum","tripicum","triticum","trop","trot","trés","tu",
"tua","tui","tuit","tum","tuum","tuz","tés","u","ubi","uenge",
"ueniam","uenie","uer","uerbum","uere","uers","uert","uertu","uerz","uesci",
"uespres","ueteres","uez","uia","uias","uicijs","uif","uim","uirgo","uita",
"uitam","uitas","uite","uitiis","uitijs","uitis","ultimum","umbre","un","une",
"unico","unitas","unitrino","uno","uns","unum","uo","uocauit","uoces","uocis",
"uoice","uolaige","uolentiers","uorrai","uorsai","uos","uostre","uostres","uou","uoulentiers",
"uous","uoustre","uouz","uox","uoz","ut","uus","ué","v","vale",
"valer","vatendo","vesci","veo","vertus","vestu","via","vias","vic","victoria",
"vif","vilai","vitas","vite","vn","vne","vnes","vng","vngs","vnques",
"vns","vo","volant","vole","volentiers","vorrai","vos","vostre","vostres","voulentiers",
"vous","vouz","voz","vus","werpir","wesseyl","xorderie","xort","y","ycy",
"yessea","ç'ai","ça","çou"
];

$c->{reading_text_stop_words_hash} = {};
foreach my $stop_word (@{$c->{reading_text_stop_words_list}})
{
	$c->{reading_text_stop_words_hash}->{normalize('C', $stop_word)} = 1; 
}


$c->{reading_text_words} = {
	"abandoner" => ["abandon","abandonai","abandonnai","abandouné","bandon"],
	"achater" => ["acater","achater","acheter","akater"],
	"acomplir" => ["acomplie","aconplie"],
	"acointer" => ["l'acointai","m'acointa"],
	"acoler" => ["acoleis","acolez","acolés"],
	"acueil" => ["acueil","acuil","agoill"],
	"adando" => ["adando"],
	"ades" => ["adiés","adés"],
	"adieu" => ["adieu"],
	"adroit" => ["adroit"],
	"ae" => ["ae","aé","aéo","aéu","éo"],
	"afaire" => ["afaire"],
	"afier" => ["afieit","afiert"],
	"afoler" => ["m'afolera"],
	"agace" => ["agace"],
	"agneau" => ["agniel","aignel","aigniel"],
	"agreer" => ["agree","m'agree"],
	"ahi" => ["ahai","ahi","ahie","ay","aï","haÿ"],
	"aide" => ["ayde","aïe","s'aïe"],
	"aider" => ["aiderés","aidier","aidiez","aidiés","m'aide","m'aiudar","m'aïst","m'aït","m'aÿt"],
	"aimi" => ["aimi","aimmi","ainmi","ajmmi","aymi","eimi","emi","emmi","enmi","eymmi","hemi","k'ainmi"],
	"ainc" => ["ainc","ains","ainz"],
	"ainsi" => ["ainsi","ainsin","ainsint","ainsit","ainssi","ajnsi","ansi","ançois"],
	"alatire" => ["alatire"],
	"alegement" => ["alegement","aligement","d'alegement","n'alegement"],
	"alegier" => ["alegier","alegiez","alegiés","aligiez","allegiez","d'alegier","d'alleger","m'aligest","ralegiés"],
	"aler" => ["aleir","aleis","aler","alez","alleis","aller","allez","aloie","alons","alé","alés","g'irai","i'aille","irai","irat","ireis","irez","irés","m'irai","n'aille","n'alez","n'alés","n'ira","n'iroie","n'iront","n'irés","s'alleis","ua","uait","uas","uat","uet","uoix","uont","va","vait","vas","vois","voise","voist","voix","voiz","vont","ralons","reuois"],
	"aleuriva" => ["aleuriua","aleuryua","luriua"],
	"all" => ["all"],
	"aloete" => ["aloete","l'aloete","l'alowette","loete"],
	"alumer" => ["aluire","aluirer","alume","alumer","alumé"],
	"amant" => ["amans","amant","amanz","amaunz"],
	"amendement" => ["amendement"],
	"amender" => ["amandeir","amander","amender"],
	"amener" => ["amaine","anmoinnent","enmaigne","enmaine","l'amaine","l'enmoinrés","m'amaine","m'amenez","t'amaint"],
	"amer" => ["aiinz","aim","aime","aimeroit","aimme","aimé","ain","aing","ainme","ainment","ainmet","aint","ama","amai","amee","amei","ameie","ameir","ameis","ameit","amer","amera","amerai","amerait","ameras","ameray","amerez","ameroie","ameroit","ameré","amerés","amet","amez","amoit","amons","amé","amés","anamer","armer","ayme","c'ameir","d'ameir","d'amer","d'amier","d'ammer","entreamez","i'aim","i'aime","i'ain","i'ainc","i'aing","i'ainme","i'ains","i'am","i'amaixe","i'amasse","i'amerai","i'amoie","i'ayme","j'aim","j'aime","j'ain","j'ainc","j'aing","j'ains","j'am","j'amaisse","j'amera","j'amerai","j'ayme","k'amaie","k'amee","k'ameie","l'aim","l'aime","l'aimme","l'ain","l'ainc","l'aing","l'ainme","l'aint","l'ameir","l'ameis","l'amer","l'amerai","l'ameroi","m'aime","m'aimes","m'aimme","m'aimmes","m'aimmet","m'ainme","m'aint","m'ama","m'amas","m'amera","m'amerait","m'amerat","m'amerez","m'amez","m'amoit","m'amé","m'amés","m'eime","n'aim","n'aime","n'aimme","n'ain","n'aing","n'ainme","n'ama","n'amai","n'amer","n'amera","n'amerai","n'amerais","n'ameroie","n'ameré","n'amez","n'amoie","n'amés","q'amer","qu'amee","qu'amer","qv'amee","s'aim","s'aimme","s'ain","s'aing","s'amera","s'amerai","s'ameray","s'ameroi","s'amerons","s'amorai","s'antraimme","s'antraimmet","s'antreimmet","t'aim","t'ain"],
	"ami" => ["ami","amie","amiet","amiete","amiette","amin","amins","amis","amiz","amj","amy","c'amis","cank'amis","d'ami","d'amie","d'amiete","d'amin","l'ami","l'amin","m'amiate","m'amie","m'amiete","n'amie","s'amie","t'amie"],
	"amor" => ["aamors","amoir","amor","amors","amour","amours","amourz","amous","amur","amurs","bon'amor","c'amors","c'amours","d'amor","d'amors","d'amour","d'amours","d'amur","d'amurs","d'amourz","k'amors","k'amours","l'amor","l'amour","m'amor","m'amors","m'amour","m'amur","malamour","q'amors","q'amours","qu'amors","qu'amours","s'amor","s'amors","s'amour","s'amours"],
	"amorete" => ["amorates","amorestes","amorete","amoretes","amorette","amorettes","amourectes","amoureite","amoureites","amourete","amouretes","amouretez","amourette","amourettes","amourettez","d'amoreites","d'amoretes","d'amorettes","d'amoureites","d'amourete","d'amouretes","d'amourettes","k'amorettes","qu'amouretes"],
	"amoreus" => ["amerous","amerouse","amerouzés","amoraz","amoros","amorose","amorous","amourat","amorous","amourat","amourez","amouros","amourous","amouré","amourés","enamoree","enamourat","enamouré"],
	"amoreusement" => ["amerousemant","amerousement","amerouzement","amoreusement","amoureusemant","amourousement","amoureusement"],
	"anel" => ["l'anelet","l'anelez"],
	"anui" => ["annuj","annuy","anoie","anui","anuye","d'ennui","ennuie","ennuit","ennuy","ennuye","m'enoye", "l'anoi", "l'anoy"],
	"anuit" => ["aneut","annuit","anuit"],
	"apercevoir" => ["aperceuoir","parsue"],
	"apeler" => ["apele","apeler","apelleir","i'apelerai","j'apelerai","j'apielerai","j'appellerai","m'apele","m'apelle"],
	"aporter" => ["aporta","apourta"],
	"aprendre" => ["aprendera","aprendés","apreneis","aprenez","aprennez","aprent","aprins","apris","s'aprendeis"],
	"assaillir" => ["m'asaut","m'assaut"],
	"assaut" => ["assault","assaulx"],
	"assavorer" => ["asauoré","asauoreit","asauouré"],
	"assener" => ["assegné","assenee","assenés"],
	"asseoir" => ["asise","assis","assiz","ceant","m'assis","seant"],
	"assoagier" => ["m'aisuaige","m'asoage","m'asoaige","m'asoshaige","m'asouage","m'assoage","m'assouage","n'assouaige"],
	"ataindre" => ["ataindre","ataint"],
	"atendre" => ["atandrai","atandre","atant","atench","atendance","atendant","atendoie","atendrai","atendre","atens","atent","attens","attent","i'aitent","i'atandoie","i'atant","i'atemps","i'aten","i'atenc","i'atenderai","i'atendoie","i'atendrai","i'atendroie","i'atent","j'atant","j'atendrai","j'attendrai","k'atent","l'atendrai","m'atant","m'atendeis","m'atent","n'atenc","n'atent","qu'atent","ratendez","ratendés","s'atant","s'atent"],
	"aunoi" => ["l'annoi","l'anoi","l'anoy","l'aunai","l'aunoi"],
	"avalabondenne" => ["aua","avalabondenne"],
	"avenant" => ["auenant","auenanz"],
	"avenir" => ["aduenir","auaigne","aueigne","aueinne","auenir","auenoit","auiegne","auieigne","auiengne","auient","auignet","aviegne"],
	"aventure" => ["auanture","auenture","aventure"],
	"bacheler" => ["bacelers","bacheleir","bacheler","bachelers"],
	"baillie" => ["bailie","ballie","baillie","balaie"],
	"baillier" => ["baille","bailler","bailli","baillier","baillir"],
	"baiselete" => ["baicelete","baicelette","baiselete","baisselete","besselete","boisselete"],
	"baisier" => ["baiser","baisier","baisiez","baisiés","baixiés","beisiez","besera","besiez","besiés"],
	"baler" => ["bal","bale","baler","balera","balerie","balez","balleir","ballerie","balés"],
	"baron" => ["baron"],
	"batre" => ["bait","bat","bateis","batera","baterat","batez","batra","batue","batés"],
	"baudor" => ["baudor","baudour","baudur"],
	"beguin" => ["begine","beguin","beguineite"],
	"bel" => ["baut","beau","beaus","beaux","beax","bel","bele","bella","belle","bias","biau","biaul","biaus","biaux","biauz","biax","biaz","biel","biele","bielle","bjau"],
	"belement" => ["belemant","bellemant","bellement","bielement"],
	"bergerete" => ["bargeronette","bargerounette","bergerete","bergeronete","bergeronnete","bergeronnette","bregeronete"],
	"biauté" => ["beautez","biautei","biauteit","biautez","biauté","biautés"],
	"biens" => ["biens"],
	"blanc" => ["blanc","blanque","blant"],
	"blasmer" => ["blameis","blamer","blamez","blamés","blasmee","blasmeie","blasmeis","blasmeit","blasmer","blasmera","blasmeya","blasmez","blasmés"],
	"blecier" => ["blesce"],
	"blond" => ["blonde","blondeite","blondete","blondette"],
	"boche" => ["boche","bochete","boucete","bouche","bouchete","bouchette"],
	"boire" => ["beuons","boire"],
	"bon" => ["boen","boene","boens","boin","boine","bon","bone","bones","bonne","bonnes","bons","bouen"],
	"bonement" => ["bonement","bonnement"],
	"bos" => ["boais","bois","boix","bos"],
	"boschage" => ["boscage","boscaige"],
	"branche" => ["branchelle"],
	"bras" => ["brais","bras","braz"],
	"brisier" => ["brisier","bruisiez"],
	"brun" => ["brun","brune","bruneite","bruneites","brunet","brunete","brunetes","brunette","brunez","bruns"],
	"buisson" => ["buissonet"],
	"burelure" => ["beurelidon","burelaribu","burelidon"],
	"camusette" => ["camusette"],
	"caroler" => ["caroler"],
	"ceindre" => ["chaindrai","saindrai"],
	"ceinture" => ["ceinturete","sainturette","senturete"],
	"celer" => ["celer","celerai","celleir","celler"],
	"cent" => ["cent","cenz"],
	"chaloir" => ["chault","chaut"],
	"chambre" => ["chambre","chanbre"],
	"chançon" => ["cançon","chan","chans","chanson","chansonettes","chançon","chançonete"],
	"changier" => ["cangie","cangier","chaingier","change","changera","changerai","changier"],
	"chanter" => ["cant","canterai","cantés","chant","chantans","chantant","chante","chanteir","chanteis","chanteiz","chantent","chanter","chanterai","chanteray","chantez","chantot","chantés","chanz"],
	"chape" => ["capelet","chaipelet","chape","chapeau","chapel","chapelet","chapiau","chapiaux","chappe","chappel"],
	"chascun" => ["cascun","cascuns","cescuns","chacun","chascun","chascune","chascuns","chaucuns","chauscun","chescuns","quancuns","quaucuns"],
	"chastel" => ["chasteau","chastel","chastelaine"],
	"chastier" => ["chaistit","chastie","chastit","chastoi"],
	"chetif" => ["caitiue","chaitif","chaitiue","cheitiue","chetif","chetis","chetiue"],
	"chevalier" => ["cheualier"],
	"chois" => ["chois","cois"],
	"choisir" => ["chesist","choisi","choisist","choisit","choisy","coisi","coisist","kieusist"],
	"chose" => ["chose"],
	"cibalala" => ["chabala","chibala","chibalala","chibele","chibera","chiberala","cibala","cibalala","ciua","ciuala","ciualala","ciualaladuriax","civa","civala","lachibele","lala"],
	"ciel" => ["ciel","cielz","ciex"],
	"clamer" => ["claim","claime","clamer"],
	"cler" => ["cleir","cleire","cler","clere"],
	"coardie" => ["coardie","couardie"],
	"coart" => ["coart","couars","couart","cowars"],
	"coie" => ["coie"],
	"cointe" => ["coente","cointe","cointement","cointise"],
	"color" => ["color","coloree"],
	"comandement" => ["comandement","commendemant","conmandement"],
	"comander" => ["comandeis","comans","comant","comanz","command","commande","commandons","commant","conmant","coumant","quemant","recoumandons"],
	"comencier" => ["comancement","comansier","comence","comencier","commencié","commencé","conmencha","conmencié","coumencier","enconmencié"],
	"compaigne" => ["conpaianete","conpaignete","conpaingnete"],
	"compaignie" => ["compaignie","compaingnie","compainz","conpaignie"],
	"compaignon" => ["compaignon","compaingnons","compengnons"],
	"comporter" => ["comportas"],
	"conduire" => ["conduie","conduira","conduis","conduit"],
	"conforter" => ["confors","confort","conforteir","conforteis","conforter","confortez","confortés","conforz","consalz"],
	"congié" => ["congiet","congié","coniei"],
	"conquerre" => ["conquestee","conquester","conquis","conquix"],
	"corage" => ["corage","corageus","coraige","courage","couraige"],
	"corre" => ["corent","corrent","keurent","queurent"],
	"cors" => ["cor","corps","cors"],
	"cortois" => ["cortois","cortoisie","courtoisie"],
	"cous" => ["cous"],
	"covenir" => ["conuenist","conuent","conuient","convent","couegne","couent","couient","couuenir","couuenist","couuient"],
	"craindre" => ["crient"],
	"crever" => ["crauent","creueir","creueront","creuerés","creuez"],
	"crier" => ["cri","crie","crieir","criem","crier","crierons","crieront","cris"],
	"croire" => ["creez","croi","croie","crois","croit","créés","recroie","recroit"],
	"cruel" => ["cruel","crueus","cruex"],
	"cruelment" => ["crueilment"],
	"cuens" => ["cuens"],
	"cuer" => ["ceur","ceurs","coeur","cuer","cueret","cuers","cver","cvers","qer","queors","quer"],
	"cuidier" => ["cuidai","cuiday","cuide","cuidoie","cuit","quidai","quide","quidie","quidiés","quidoie"],
	"daigner" => ["daigne","daigniez","daignoit","deigne","deigniés","deignoit","dengne","doigne","doigneis","doignest"],
	"damage" => ["damache","damage","damaige","domage"],
	"dame" => ["dama","dame","dames","damme","madame"],
	"damoisele" => ["damoisele","damoiselle","demisele"],
	"dance" => ["dance","dancele","danse"],
	"dancer" => ["dancer","dancerai","dancez","dancier","danciez","dancés","dansser","dançar"],
	"darion" => ["darion"],
	"deable" => ["deables","deaubles","diables","dyable","dyaubles"],
	"debonaire" => ["deboinaire","deboinere","debonaire","debonere","debonnaire","debonnaires","debonoires","debounaire"],
	"debonairement" => ["debonairement"],
	"debonaireté" => ["deboinereté","debonairetez","debonaireté","debonairetés","debone","debonereté","debonnaireté","debounereté"],
	"debrisier" => ["debris","debrise","debrisent"],
	"decevoir" => ["deceuans","deceuoir","decevoir","deceü","deceüe","decheuoir","deseuoir"],
	"deduire" => ["deduire","dedus","deduxans","desduire"],
	"deduit" => ["deduis","deduit","desduit"],
	"defendre" => ["deffendeis","deffendez","deffendrai","deffendre","deffendreis","deffendés","deffent","deffondés","desfendre","desfent"],
	"deine" => ["deine"],
	"delarandurei" => ["delaradurelle","delarandurei"],
	"delaridon" => ["delaridon"],
	"delit" => ["delis","delit","delite","deliz"],
	"delivrer" => ["deliura","delivra","delivrés"],
	"delle" => ["delle","deme"],
	"delurele" => ["delurele","deluriau","deluriele","delurot","luroy"],
	"demain" => ["demain"],
	"demander" => ["demanc","demand","demande","demandee","demander","demandez","demanrait","demanrat","demant","demendez","demendz","qier"],
	"demener" => ["demaine","demainne","demeinne","demener","demenne","demenra","demenrra","dement","demoinne"],
	"demorer" => ["demeure","demeurés","demoree","demorei","demoreit","demorer","demorez","demorrés","demoré","demorés","demour","demoure","demouree","demourer","demourez","demouré","demourés"],
	"departir" => ["depairt","depars","depart","departie","departir","departirai","departirons","departiront"],
	"deporter" => ["deport","deporter"],
	"deservir" => ["desert","deserui","deseruie","deseruit","deservie","desserui","desseruie"],
	"desir" => ["desir","desirant","desire","desiree","desireie","desireis","desirree","desirrés","dezir","dezirouze"],
	"desloial" => ["desleaus","desloiaus"],
	"destraindre" => ["destaindre","destraigne","destraignent","destraigniez","destraindre","destraint","destrant","destrent"],
	"Deu" => ["deu","deus","deux","dex","dieu","dieus","dieux","diex","diu","dius","diux","dix","dié","djeus","djex","dues","duez","dé","endieu"],
	"deurelidele" => ["deurelidele","deurelidot"],
	"deus" => ["deus","deux","dous","dui","ii","ij"],
	"devenir" => ["deuendra","deuendrai","deueneis","deuenez","deuenir","deuenrai","devient"],
	"deviner" => ["adeuiner","adevinez","deuiner"],
	"devoir" => ["deuez","deuoit","deuons","deuroit","deués","devons","devuons","deüst","doi","doibt","doie","doit","doiue","doueroie","douoir","doy"],
	"dire" => ["di","dira","dirai","dirait","diraiz","diray","dire","direz","diroi","diroie","diroiz","dirra","diré","dirés","dis","diseteus","disoit","dist","dit","dite","dites","ditez","dittes","dixoit","diz"],
	"dis" => ["dix","x"],
	"diva" => ["diua","diuai"],
	"dodele" => ["do","dele","dodele","dodelle","dododo","dondele","dundele","dundeus"],
	"doi" => ["doi","dois","doit","doy"],
	"dolent" => ["dolans","dolant","dolante","dolens","dolent","dolente","doulant"],
	"dolor" => ["delour","dol","doloir","dolor","dolors","dolour","dolours","dols","dolur","dolurs","doul","douleur","douleurs","doulor","doulors","doulour","doulours","dueil","duel","duels","duelz","duil","doloir"],
	"doloreusement" => ["dolorouzement"],
	"doloros" => ["delirous","dolereus","dolereux","dolerez","doleroz","doleureus","doulerous","douloureux"],
	"dondenne" => ["dondenne"],
	"doner" => ["doig","doing","doins","doinst","doint","don","donait","done","donee","donei","doneir","doneis","doneit","doneiz","doner","donez","donne","donnee","donnei","donneie","donneis","donner","donneray","donney","donnez","donné","donnés","donois","donrai","donray","donrray","donré","doné","donés","dorai","dorré","doune","dounee","douner","dounez","douné","dounés","dourrai"],
	"dorelot" => ["deurenleu","deurenlev","doalot","doralot","doranlot","doreleu","dorellot","dorelo","doreloit","dorelot","dorenleu","dorenlo","dorenlot","dorenlou"],
	"doriaus" => ["doreaus","dorele","dori","doriaus","doriaux","doriax","dorie","doudie","doura","doureaus","dourele","doureles","douri","douriaus","dourie","duduriaus","dural","durau","dureau","dureaus","dureaux","durei","durele","dureles","durelle","duri","duriau","duriaus","duriaux","duriax","durie","durien","duron","durot","duré","ladurele","laduriaus","ladurie","laladurete","ualidorele","ualidoré","valaliduré","vali","validoriax"],
	"dormir" => ["dorme","dorment","dormez","dormi","dormir","dormira","dormirai","dormiras","dormiray","dormirez","dormiroit","dormirés","dort","endormi","endormie"],
	"doucement" => ["docement","douceitement","doucement"],
	"douçor" => ["douchour","douchours","doulçor","dousour","douçor","douçour","douçours"],
	"dous" => ["doce","doche","dolz","douc","douce","douces","doucete","doucette","douceurs","douche","douchette","doulce","doulces","douls","doulx","doulz","dous","doux","douz","dox","doz","tresdouce","tresdouz"],
	"douze" => ["douze","xii"],
	"droit" => ["drois","droit","droite","droiz"],
	"droiture" => ["droiture"],
	"druerie" => ["dru","drue","druerie","drues"],
	"duel" => ["deuil","deul","deuls"],
	"dur" => ["dures","durete","durette"],
	"durer" => ["dure","dureir","dureis","durer","durerés","duret","dureya","durez","durra","duré","durés"],
	"embler" => ["amblee","amblei","amblé","emblé","enbleit","enblé"],
	"emporter" => ["j'emporte","l'emport","l'enport"],
	"endurer" => ["andurer","endure","endureir","endurer","endurez","enduroi","enduron","enduré","endurés","i'enduir","i'endur","j'endur","l'endure"],
	"enemi" => ["anemi","anemis","anemmi"],
	"enporter" => ["enporta"],
	"enseignier" => ["enseigner","m'ensaigne","m'ensaingne","m'ensegne","m'enseigne","m'enseigniez","m'enseigniés"],
	"entendre" => ["antendre","entendez","endendray","entendre","endentroit","entendroy","entendés","j'entendray","m'entendroie", "entendray", "entendroit" ],
	"entier" => ["entier","entiere","entire"],
	"entierement" => ["entieremant"],
	"entremetre" => ["m'entremete"],
	"entrer" => ["antrai","entree","entrer","entrez","entré","entrés"],
	"entroblier" => ["entr'oblier","entr'oublier","entroubliee","m'antroblie","qu'entrobliee"],
	"envier" => ["anvie","d'envie","enviz"],
	"envieus" => ["anious","anvïous","enuieus","enuious"],
	"envoisier" => ["anuoixie","anvoisie","anvoixie","enuoisie","enuoisiés","enuoixiés","envoisie","m'anuoise","m'enuoise","m'enuoiserai","m'envoise","ranuoisie","ranvoisie","renuoise","renuoiserai","renuoisie","reuoisier","renuoisies","renuoisiez","renuoisié","renuoisiés","renvoisera","renvoisie","renvoisier","renvoisiez","renvoisiés","renvoysiez", "renuoisier"],
	"envoier" => ["anuoie","enuoi","envois","m'enuoit","m'envoie","renuoit","renvoit"],
	"esbaudir" => ["esbaudir","esbaudis"],
	"escolter" => ["escote","escoute"],
	"escondire" => ["escondis","l'escondire"],
	"escrire" => ["escript","escripte","escris","escrit"],
	"esjoïr" => ["esioïr","esioïs","resioïr","resjoïr"],
	"esloignier" => ["eslognie","esloignie","esloigniet","esloigniez","eslongie"],
	"espaourer" => ["espaouree"],
	"esperance" => ["esperance","m'esperance"],
	"esperer" => ["esperant","espereir","esperer"],
	"espoenter" => ["enpoentee","espauentee","espoantee","espoentee"],
	"espoir" => ["espoair","espoi","espoir"],
	"espringuier" => ["espringas","espringuaz","espringuez","espringuiez","espringués","l'espringuier"],
	"espris" => ["espris"],
	"estraine" => ["estrainne","estrene","estrine"],
	"estovoir" => ["l'estuet","m'estuet"],
	"estrange" => ["estraigne","estrainge","estrange","estrengne"],
	"esveiller" => ["esueilliez","eueilliez","l'esueillerai","l'esuellerai","l'esvellerai","m'esuaille","m'esueille","resueille","resueillent","resuelle"],
	"eure" => ["eure","eures","heure","heures","houre"],
	"eureusement" => ["eüreusement"],
	"eya" => ["ea","eai","eein","eeus","ei","eo","eois","eou","ey","eya","eyal","eyaut","eyent","eyeus","eyois","eyoit","eyous","eyr","eyt","eyu","eyuer"],
	"faillir" => ["fail","faille","failli","faillie","faillir","faillis","faillit","fali","fallier","fallir","faut"],
	"faindre" => ["faindrai","faindre","faing","faingi","fau"],
	"faitis" => ["faitissete","faitissette"],
	"faloir" => ["faudra","faudrai","faudroit","faudront","fauldra","faura","fauriez","fauront","faurra"],
	"falser" => ["faceir","fauce","fauceir","faucer","faul","faulce","faus","fausai","fause","fausee","fauser","faussai","fausse","fausser","faussera","fausserai","faussé","faussés"],
	"faussement" => ["faucement"],
	"felon" => ["fellons","felon","felons"],
	"feme" => ["fame","feme","femme"],
	"fi" => ["fi","fj"],
	"fille" => ["fille"],
	"fin" => ["fin","fin","fine","fines","fins","finz","fjnes"],
	"flajol" => ["flagieu","flagol","flagoler","flaioler","flaiot"],
	"flor" => ["fleurs","flor","flors","flos","flour","flours","flourz","flur"],
	"florir" => ["flori","florie","flourie","flourir"],
	"foi" => ["foi","foy"],
	"foil" => ["foilli","fueille","fueilli"],
	"fol" => ["fol","fole","folle","fols","folz","foul","foulz","fous","foux","fox"],
	"folement" => ["folement"],
	"folie" => ["folage","folaige","folie","foliete","follour","folor","folur"],
	"foloier" => ["filiier","foliier","foliser","folloié","foloi","foloie","foloier","foloié"],
	"gai" => ["gai","gaie","gais","gay"],
	"garçon" => ["garchon","garçon"],
	"garder" => ["gairdeir","gairderai","garde","gardeis","gardeiz","garder","garderai","garderoit","gardez","gardés","guardee","guardez"],
	"garir" => ["garie","garir","garira","garirai","garirat","garis","garist","garit","garrai","garray","garrirai","guarie","guarira","guariroie","guerira","guerirai","guerirait","guerireiz","guerist","gueriz","guerra","guerrai"],
	"garison" => ["garison","gherredon","gueredon","gueridon","guerison","guerredon"],
	"gaudine" => ["gaudine"],
	"gens" => ["gens","genz","iant","ianz"],
	"gent" => ["gens","gent","gente","gentee","gentils","gentis","genz","iente"],
	"gnif" => ["gnaf","gnauf","gnief","gnif","gnof","gnouf"],
	"grace" => ["grace","gracieuse","gracieusette","graciouse"],
	"grant" => ["grand","grans","grant","granz"],
	"gré" => ["gree","grei","greif","greis","greit","grez","gré"],
	"grevance" => ["greuance","greuence"],
	"grever" => ["greuee","greueir","greueit","greuer","greuet","greué","grevet","grevé","grieue","griué"],
	"grief" => ["grief","griez","griés"],
	"guerpir" => ["guerpi","guerpie","guerpisiez"],
	"guiler" => ["ghille","guile","guiler","guiller","guilleurs","guillier"],
	"haer" => ["haez","haieiz","haiez","hais","hait","haï","haïr","haïs","haÿr","hee","hei","heit","het"],
	"hahai" => ["ahai","hahai","hahye","haihai"],
	"haro" => ["hairo","hareu","hareus","haro","harou","herou"],
	"haut" => ["hault","haut","haute"],
	"hautement" => ["hautement"],
	"hé" => ["aé","e","é","hai","hé", "éé", "ééé" ],
	"helas" => ["elais","elas","helas","halas"],
	"hom" => ["hom","home","homme","hons"],
	"honir" => ["honi","honie","honir","honis","honit","honiz","honni","honnie","honnis","honnist","honniz","honny","houni","hounis","hounist","oniz"],
	"honte" => ["hontage","honte"],
	"hu" => ["hu"],
	"huer" => ["huer"],
	"hui" => ["hui","huy"],
	"hureliva" => ["hureliua","hureliuai","huva","heuva","heuvien"],
	"jamais" => ["iamais","iamaix","iamez","iamés","jamais","jamaix","jamés"],
	"jalousie" => ["gielos"],
	"jalous" => ["ialos","ialous","ialousie","ialouz","jalous","jalousie","jaloussie","jaloux"],
	"Jesus Christ" => ["crist","criz","iesus","ihesu","ihesucris","jhesu","jhesucris","jhesucrist","jhesucriz"],
	"jeu" => ["gieu","gieus","ieu","ieux","jeux"],
	"joene" => ["iennes","iennete","ieune","ioeme","ioene","ioenete","ioenne","ioine","ione","iones","ionete","ionette","iouene","iouenete","jeunete","joenne","jone"],
	"joer" => ["ioeir","ioer","ioier","iouer","iue","iueir","iuer","iut","jeut","joer","joiant","jouer","jut","juweiz"],
	"joie" => ["goie","ioe","ioiant","ioianz","ioie","ioieuse","ioir","iois","ioye","joie","joiee","joye"],
	"joint" => ["iointes","jointe","jointes"],
	"joïr" => ["ioïr","reioïr"],
	"jolieté" => ["iolietei","iolieté","ioliuetez","ioliueté","ioliuetés","ioliveté","joliuetés","joliuetez", "joliveté"],
	"jolietement" => ["ioletement","ioliement","iolietement","ioliettement","ioliuement","ioliuetement","jolemant","joliement","jolietemant","jolietement","joliettement","joliuement"],
	"jolif" => ["iolete","ioli","iolie","ioliete","iolietes","ioliette","ioliettes","iolif","iolis","iolit","ioliue","ioliuet","ioliuete","ioliuetes","iolive","jolivet","ioliz","joli","jolie","joliete","joliette","joliettes","jolif","jolis","jolit","joliue","joliuetes","joliuettes","jolive"],
	"jor" => ["ior","iors","iorz","iour","iours","iourz","jor","jors","jorz","jour","jours"],
	"jurer" => ["iureit","iuré"],
	"lairele" => ["laierele","lairele"],
	"laissier" => ["laira","lairai","lairait","lairay","laire","lairez","lairiai","lairoie","lairons","lairés","lais","laise","laissai","laisse","laissent","laissiez","laissié","laissiés","laist","lait","laixe","laixet","lara","larai","lareis","last","leira","leirai","leisse","leissier","leit","lerai","leray","lerez","leroie","leré","lerés","lessai","lesse","lessent","lessiez","lessié","lest","let"],
	"langor" => ["langor","langour","languir","languirai","languissant","languissiés","languit","languor"],
	"languir" => ["laguir"],
	"lareu" => ["lareu"],
	"legier" => ["legier"],
	"legierement" => ["legierement"],
	"lever" => ["leuee"],
	"libodaine" => ["libodainne","libodine"],
	"lié" => ["liez","lié","liét"],
	"liement" => ["liement","liéement","lyement"],
	"lieu" => ["leu","lieu","liu"],
	"loer" => ["lo","loeie","loeir","loer","loi","los","lot","lout","lox","loz"],
	"loing" => ["loig","loing","loins","léenz"],
	"lointain" => ["loigtaigne","loigtaine","lointainne","lontaigne","lontain","lontaing","lontaingne","lontainne", "lontaine"],
	"lonc" => ["lonc","longue","lons","longe"],
	"longement" => ["longement","longhement","longuement","longuent"],
	"loial" => ["laial","leal","leaul","leaus","leaux","leial","loal","loial","loials","loialz","loias","loiau","loiaul","loiaus","loiax","loyal","loyalz"],
	"loialté" => ["leaultei","leauté","loialteis","loialteit","loiaulteit","loiautez","loiauté","loiautés"],
	"loiaument" => ["laiaument","lealment","leaulment","leaumant","leaument","leialment","leiamant","leiaument","liaument","loamant","loialment","loiaulment","loiaumant","loiaument","loiaumet","loyaulmt","loyaument"],
	"main" => ["main","mains","mein","meins"],
	"maintenir" => ["maintaigne","maintanrai","maintendrai","maintenir","mainterai","mainterrai","maintienent","maintiennent","maintient","mentainrai"],
	"maintien" => ["mentiens"],
	"mal" => ["mal","male","mals","malt","malx","malz","mau","maul","mauls","maulx","maulz","maus","maux","mauz","max"],
	"malade" => ["malades","maladie","malaides"],
	"malage" => ["malage","malaige"],
	"malement" => ["malement"],
	"maleur" => ["mescheance","mescheans","mescheanz","meschief","mescreance"],
	"maleuros" => ["maleuroz"],
	"malvais" => ["maluais","mauais","mauaistié","mauuais","mauuestié","mauuez","mauués","mauvais","mauvés","maués"],
	"mamele" => ["mamele","mameletes","mamelettes"],
	"mander" => ["mandez","mandé","mandés","mant"],
	"mangier" => ["mengerons","mengier"],
	"mantel" => ["mentel"],
	"mari" => ["mari","maris","marit","mariz","mary"],
	"mariage" => ["mariage","mariaige","mariai"],
	"marier" => ["maria","marie","mariee","marieie","marieir","marier","mariera","marierai","marieray","mariez","marié","mariés"],
	"Marie" => ["marie"],
	"matin" => ["main","matinee"],
	"mener" => ["maignent","maine","mainent","mainne","mainreiz","maint","meine","meinne","menant","meneis","mener","menez","menons","menrai","menrons","moine","moinne","moinreiz","moinrons","moinrés"],
	"mentir" => ["mant","mantir","mens","ment","menti","mentir","mentit"],
	"merci" => ["merce","merchi","merchis","merchit","merchy","merci","mercis","mercit","merciz","mercy","mersis","mersit","mierchi","mierci"],
	"mere" => ["meire","mere"],
	"meschoisir" => ["meschoisy","meschosi","mescoisi"],
	"mesdisant" => ["medisans","medissans","medixans","medixant","mesdisans","mesdisant","mesdisanz","mesdissans","mesdixans","mesdis"],
	"mesfait" => ["meffaire","meffait","meffet","mesfait"],
	"mesnage" => ["mainage","mesnage","mesnaige"],
	"mesprendre" => ["mespris"],
	"message" => ["message","messages","messaige"],
	"mestier" => ["mestier"],
	"metre" => ["mectre","meit","met","mete","meteis","metez","metre","mettre","metés","meïst","mis","mise","mist"],
	"mignot" => ["mignos","mignot","mignote","mignoz","mingnot"],
	"mignotement" => ["mignotemant","mignotement","minoigrement","minoigtement"],
	"mignotise" => ["mignostie","mignotise","mignotixe","mingnotise"],
	"mil" => ["mil","mile"],
	"moine" => ["moignes","moine"],
	"mont" => ["monde","mons","mont","monz","munt"],
	"morir" => ["morai","morait","morir","morra","morrai","morrez","mors","mort","moru","morut","morz","moura","mourir","mourrai","mourroi","muer","muert","muir","mur","muyr"],
	"mot" => ["mot"],
	"movoir" => ["mouoir","mouuoir","movoir","muet"],
	"musardie" => ["musardie"],
	"musart" => ["musairs","musant","musar","musars","musart","muzairs","muzant","muze"],
	"navrer" => ["nauree","naurei","naureis","naureit","naurez","nauré","naurés","navré","noble","noblesce","noblette"],
	"noce" => ["noces"],
	"nom" => ["nom","nons"],
	"nomer" => ["nomeir","nomer","nommer","noumee"],
	"nonne" => ["nonette","nonne","nonnete","nonnette","nounain"],
	"norrir" => ["norie","norrie","nouri","nourreture","nourri"],
	"noter" => ["note","notes","notois", "notoit"],
	"novel" => ["nouel","nouele","noueles","nouelet","noueletes","nouelle","nouelles","nouiaus","nouuel","nouuele","nouueletes","nouuelletes","nouuellettes","nouuiau","nouuiel","nouuieles","nouvel","nouveles","nouvellettes"],
	"noveletement" => ["nouellement","nouueletement"],
	"nuire" => ["nuira","nuisoit","nuist","nuit"],
	"nuit" => ["nuit","nuyt"],
	"obeir" => ["obeir","obeïr"],
	"oblier" => ["c'oblier","m'oblieis","m'oblieiz","m'obliez","m'obliés","m'oublie","m'oubliez","m'oubliés","m'ublit","n'obli","n'oblieiz","n'oblierai","n'oubli","n'oublierai","obli","oblie","obliee","oblier","oblierai","oubli","oublie","oubliee","oublieit","oublier","oublierai","oubliez","oubliier","oubliés"],
	"ocire" => ["l'ocirroie","l'ocist","m'occhie","m'occhirra","m'occirra","m'occist","m'occit","m'ochi","m'ochie","m'ochient","m'ochira","m'ochirra","m'ochirrés","m'ochist","m'ochiés","m'ocidrait","m'ocie","m'ocieis","m'ocieiz","m'ocient","m'ociez","m'ocira","m'ocirait","m'ocireis","m'ocireiz","m'ocirez","m'ociront","m'ocirra","m'ocirreis","m'ocirrez","m'ocirroiz","m'ocirrés","m'ocirés","m'ocist","m'ocit","m'ociés","m'orciroiz","m'orcirrez","m'oscist","m'osidrait","m'osie","m'osient","m'osist","n'ocieis","n'ociez","n'ocirrez","n'ociés","oci","ociroie","ocis","ocit","ocys"],
	"ochoison" => ["d'achoison","l'ochoison","l'ocoison","ochoison","oquison"],
	"odeli" => ["deli","delio","odeli"],
	"oeil" => ["eill","elz","eul","eulz","eus","euz","huil","ieulz","ieus","ieuz","iex","l'eul","l'ueil","l'uel","oeil","oeill","oel","oeul","oil","ouel","ueil","yeulx","yeux","yex"],
	"oeuvrer" => ["oureir","l'ueure"],
	"oïr" => ["i'oi","i'oie","j'oi","j'oï","l'orrez","l'orrés","oez","oiiés","oiés","orrez","oï","oïr"],
	"oisel" => ["l'oiselet","oiseillon","oiseillons","oisellons","oiselons","oisillon","oisillons","oyseillons","oysillons"],
	"oix" => ["oix"],
	"onor" => ["c'onors","c'onours","d'onneur","d'onor","d'onour","deshonur","hennor","hennorez","hennour","henoree","henours","honneur","honnour","honor","honors","honour","honur","hounour","hounours","k'onours","l'onor","qu'oneurs","s'eneur","s'oneur","s'onor"],
	"onorer" => ["honnourés","honoreis","honorez","honorés"],
	"orguil" => ["orgoel","orgoil","orgueil","orgueilg","orgueill","orguel","orguilleusette"],
	"oser" => ["i'osasse","i'osoie","i'oussexe","l'os","l'ose","l'osoie","l'ozoie","n'olz","n'os","n'ose","n'oz","os","s'osaixe","s'ose"],
	"oster" => ["osteir","osteis","oster","ostez","ostés"],
	"otroier" => ["m'ostroi","m'otriiés","m'otroi","m'otroie","otrai","otrie","otroi","otroie","otroit","ottrie","s'otroie"],
	"ovrir" => ["ourez"],
	"paor" => ["paor","paour","paours","poour","pouur"],
	"paradis" => ["paradis","pareïs"],
	"parçonerie" => ["parchonerie","parchonnerie","parsonerie","parçonerie","parçonnerie","perçonnerie"],
	"parçonier" => ["parçoniers"],
	"pardoner" => ["pardonez","pardonnee","pardonnez","pardonnés","pardonés","pardounee"],
	"parler" => ["pairleir","parelle","parleir","parleis","parlement","parler","parlez","parliere","parole"],
	"partir" => ["pairt","part","parti","partir","partira","partirai","partiroi","partiré","partis","partés","pertirai","pertirait"],
	"parvenir" => ["paruient"],
	"passer" => ["paisse","pascent","passe","passent","passer","passerai","pessent"],
	"pastorele" => ["pastorele","pastorelle","pastourele"],
	"pasture" => ["pasture","pasturrons"],
	"païs" => ["païs","païx","paÿs"],
	"peine" => ["paine","paines","painne","peine","peinne","pene","poene","poine","poinne"],
	"pendre" => ["pendre","penduz"],
	"penser" => ["pance","pancee","panceir","panceirs","pancer","pans","panse","pansee","panser","pansez","pansé","pencee","penpense","pens","pensant","pense","pensee","penseir","pensent","penser","pensers","pensez","penssai","penssant","pensse","pensser","penssers","penssé","pensé","pensés","repenser"],
	"perdre" => ["esperdus","perc","perch","perdrai","perdu","perdue","perdues","perdus","perdut","perdés","pert","pierdues"],
	"pervenche" => ["peruenche","venke","venque"],
	"petit" => ["petit","petitet"],
	"pie" => ["pie","piot"],
	"piteus" => ["piteus","piteuse","pitous"],
	"pitié" => ["pieteit","pitei","piteit","pitiet","pitié","pitiés","pité","pités"],
	"plaindre" => ["plaig","plaign","plain","plaindre","plaing","plaint"],
	"plaire" => ["plai","plaira","plairait","plaist","plait","pleist","plera","plere","plest","pleüs","pleüst"],
	"plaisant" => ["paisans","plaisans","plaisant","plaisanz","plaixans","plaixant","pleisant","plesant"],
	"plaisamment" => ["plaisamment"],
	"plaisir" => ["plaisir","plaixir","pleisir","plesir"],
	"plein" => ["plaine","plainne","plains","plein","pleine"],
	"plorer" => ["enplorra","pleure","pleurer","plorant","plore","plorer","ploure","plourer"],
	"poindre" => ["poignent","poingnent","poins","point","poize"],
	"poissant" => ["poisance","poissans"],
	"pooir" => ["neporoie","peult","peus","peut","poent","poet","poez","poi","pois","poist","poit","pooir","poons","pora","porai","poray","poroie","porra","porrai","porret","porrey","porroie","porroit","porés","pot","pouez","pourez","pourrai","pourrey","pourroie","pu","puet","puez","puise","puisse","puissent","puist","puix","puixe","puiz","pux","puxe","pués","reporoie","reporroie"],
	"porter" => ["port","porta","portas","porte","porteir","porter","pourtei"],
	"povre" => ["poure","poures"],
	"pré" => ["pré","prés"],
	"premier" => ["premier","premieres","premiers","prumieres"],
	"prendre" => ["enprandre","praigne","praingne","prandre","prandroie","prant","pregne","preigne","preignent","prend","prendeis","prenderai","prendra","prendrai","prendre","prendroie","prendés","prenez","prennés","prent","prenés","prest","prins","print","pris","prise"],
	"present" => ["presant","present"],
	"preu" => ["preu","preux","preuz","prous","proz"],
	"prier" => ["pri","prie","prier","priez","priiés","priés","proi","proiant","proie","proiiés","proiés"],
	"pris" => ["prix","priz"],
	"prisier" => ["prisier"],
	"prison" => ["l'enprisonnee","prison","prisonniers","prixon","prizon"],
	"prochain" => ["procaine","prochain","prochaine","prochainemant","prochainne"],
	"prometre" => ["promectre","promettre"],
	"prover" => ["proeue","prouerai","prueue"],
	"pucele" => ["pu","puce","puceille","pucele","pucelete","pucelle","puchele","puchielle"],
	"quatre" => ["quatre"],
	"quedonda" => ["quedonda","quedondi"],
	"quere" => ["acquise","kier","qer","quer","querai","querez","querrai","quier","quiert","quir","quis","quise"],
	"quinze" => ["xv"],
	"rage" => ["rage","raige"],
	"raison" => ["raison","raisons","raixon","reison","reson","resons"],
	"ramee" => ["raim","raimme","rain","ramee","ramé"],
	"ramener" => ["ramaint","ramenee","ramenez"],
	"recovrer" => ["recoureir","recourer","recouré","recouuree","recouurer","recouuré"],
	"regarder" => ["d'eswarder","esgair","esgairt","esgar","esgarde","esgardeis","esgarder","esgardés","esgart","resgardez","resgars","resgart","resgarz","rewars"],
	"regart" => ["regairt","regard","regardai","regardant","regarde","regardez","regardés","regars","regart","regarz","regaz","rigars"],
	"resconforter" => ["desconforte","desconfortee","reconforte","reconforteir","reconforter","resconforteis"],
	"remanoir" => ["remaingne","remaint","remait","remandra","remanoir","remenans"],
	"remembrer" => ["menbre","remembrance"],
	"remirer" => ["remir"],
	"rendre" => ["rans","rant","ren","renc","rende","rendent","rendez","rendre","rendroit","rendré","rendt","rens","rent"],
	"renoveler" => ["renouele","renouuele"],
	"renvoisiement" => ["renuoisiement","renvoisiement"],
	"repentir" => ["repant","repantez","repantir","repen","repent","repente","repenterai","repentez","repentir","repentira","repentirai","repentirait","repentiray","repentons","repentés"],
	"reporter" => ["reportez","reportés"],
	"reposer" => ["repos","reposeir","reposer","reposon"],
	"requere" => ["reqerrai","reqier","requier","requise"],
	"revenir" => ["reuenderont","reuenez","reuenue","reuenuz","reuenés","reuienne","reuient"],
	"reverdie" => ["renuerdie","reuerdie"],
	"reveoir" => ["reuairai","reueoir","reuerrai","reuerré","reuoer","reuoie","reuoir","reuëoir","reverrai","reverré","revoie","revoye"],
	"rire" => ["ri","rians","riant","rirai","rire","ris","rist","rit","riz"],
	"rose" => ["rose","rosier"],
	"rossignol" => ["roissignolet","rosignol","rossignol","rossignolet","rossingnol","rousignol","rousignollet","roxingnol","roxingnols"],
	"sade" => ["sade","sades","sadete"],
	"saderalidon" => ["laridon","sadela","sadelaridon","sadelarire","sadeliua","sadera","saderala","saderaladon","saderali","saderalidoré","saiderora","lidoré","liduré","liredurei"],
	"saige" => ["sage","sages","saige","saiges","saigette"],
	"saint" => ["sains","saint","sainte","sainz","seinz"],
	"saisir" => ["saisi","saixi","saixit","saizi"],
	"saison" => ["saison","seson"],
	"saluer" => ["saluee","salueir","salueis","saluez","salus","salut","salués"],
	"savoir" => ["sache","sachiez","sachiés","safret","sai","saiche","saichiez","sarai","sarez","sariés","saroie","saroit","saront","sarés","saueis","saueront","sauez","sauiés","sauoir","sauoit","saurai","saurait","saurez","sauriez","sauroie","sauroit","sauront","saurés","saués","saverai","savoit","savront","say","sçai","sçauoir","sçauront","sçaués","sçavez","sçavoir","sçay","scet","seit","set"],
	"savoreus" => ["saouree","saoureux","sauerosete","sauerouse","sauerousete","sauerouze","sauerouzette","saueroz","sauerus","saueureus","sauoreus","sauoreuse","sauoreusete","sauorosete","sauouree","sauoureus","sauoureuse","sauoureusete","sauoureusette","sauoureux","sauouros","sauourosete","sauourous","sauourousete","sauuereux","saverouze","savoreus","savoreusete","savoros"],
	"secors" => ["secorrés","secors","secorés","secourez","secourre","secours","secourés","soucourés"],
	"seignor" => ["seignor","seignorie","seignourie","seignur","signorie","signourie","singnourie"],
	"sejor" => ["seior","seiour","sejour"],
	"sembler" => ["samblance","samblant","samble","sanbleroit","sanlant","semblance","semblant"],
	"sentir" => ["sant","santez","santi","santit","sen","senc","sench","sens","sent","senteiz","sentent","sentez","senti","sentir","senté","sentés","senz"],
	"servir" => ["serf","sert","serui","seruice","seruie","seruies","seruir","seruira","seruirai","seruiroi","seruisce","seruise","seruixe","servi","services","servir","servirai","sierui","sieruir"],
	"simple" => ["simple","simplete","simplette","sinple"],
	"sire" => ["sir","sire","sires","sjre"],
	"sofrir" => ["seuffre","soffrir","sofrir","sosfrir","souffrir","soufrir","soufrés","sousfrir","sueffre"],
	"sol" => ["seule","seulete","seulette","seullete","seullette","soul","soule","soulette"],
	"solas" => ["solais","solas","solaus","solaz","soulas","soulaus","soulaz"],
	"soloir" => ["soloie","souloie","sueil","suel","suieil","suil"],
	"songe" => ["songe","songier","songoie"],
	"sorprendre" => ["seurpris","seurpriz","sopris","sorprendre","sorpris","sospris","soupris","sourpris","souspris"],
	"sospir" => ["sopir","sospir","sospirs","soupir"],
	"sospirer" => ["sopireir","sospirer","soupirant","soupirer","souspirant","souspirer"],
	"sostenir" => ["sostient","soutenez","soutient"],
	"sosvenir" => ["resosuient","resouient","resouuient","sosuiegne","souaigne","soueigne","souiegne","souiengne","souigne","souueigne","souuiegne","souuiengne","souuienne","souuient","souuigne","souvigne"],
	"sot" => ["sot","sotte"],
	"tart" => ["tart"],
	"tendre" => ["tench","tendez","tendrai","tendre","tendront","tendu","tenrai","tenroit"],
	"tenir" => ["taig","teent","teignent","teneis","tenent","tenez","tengne","tenir","tenist","tenoie","tenoye","tenés","tieg","tiegne","tiegnent","tien","tienent","tieng","tiengne","tiennent","tiens","tient","tinent","ting","tint"],
	"tens" => ["tens","tans","tanz","temps"],
	"terre" => ["terre"],
	"tesmoignier" => ["tesmoignent"],
	"tochier" => ["atouche","n'atouche","n'atoucherez","n'atoucheroiz","n'atoucherés","n'atouchiez","n'atouchiés","touche","toucher","touchier"],
	"toler" => ["tolez","tolt","tolu"],
	"torcher" => ["torcher"],
	"torment" => ["tormant","torment","tormente","tourment"],
	"torner" => ["tornanz"],
	"tornoiement" => ["tournoiement"],
	"traili" => ["traili","traire","trairi","trairire","trarire"],
	"traïr" => ["trahi","trahie","trahir","trahirai","trahis","trahison","trahy","traï","traïr","traïs","traïson","traïssent","traïsun","traït","traïxon","traïz","traÿ","traÿson"],
	"traire" => ["traez","trahet","trahez","trai","traie","traiez","traire","trairés","trais","trait","traités","traiés","tray","treez","treiez","tret","treés","tré"],
	"travaillier" => ["trahoulier","trauaille","trauailliez","trauailliés","trauaillé","traual","trauaus","traueilliez","trauelliés","trauilliez","trauilliés","trauoiller","traveilliez"],
	"trebuchier" => ["trebuchié","trebucier"],
	"trente" => ["trente"],
	"triboudaine" => ["triboudaine","triboudainne","triboudel"],
	"trichier" => ["trice","triche","tricherie"],
	"tridon" => ["tridenne","tridon"],
	"triquedondaine" => ["trikedondaine","trikedondainne","trikedondene","trikedondenne","triquedondele"],
	"triste" => ["triste","tristor"],
	"trois" => ["iii","trois","troys"],
	"trover" => ["retrouuee","treuue","troeue","trouai","trouaist","trouee","trouees","trouei","troueie","troueir","troueit","trouer","trouerai","trouerez","trouerés","trouez","trouuai","trouuee","trouuees","trouuer","trouuerai","trouué","trouvai","trouvee","trouver","trouvé","troué","trovei","trover","trové","truis","truix","trux"],
	"truffer" => ["truffe","truffes"],
	"tuer" => ["tue","tuez"],
	"turelure" => ["teirelire","teireliredon","teureleure","tuereleure","turelure","turelicta","turelutea","turulurita","turuluruta","tura","turait","ture","tureleure"],
	"uis" => ["l'uis","l'uix","l'uys"],
	"umblement" => ["humblement"],
	"usage" => ["usage","vsage","vsaige"],
	"user" => ["s'uze","useir","vseir"],
	"vadeure" => ["ua","uadeurelidot","uadi","uadoie","uadou","uadreu","uadu","uaudeure","va","vadalaridon","vadelarirondé","vaderalidou","vadeure","vadeurelidele","vadeurelidot","vadou","vadourenne","vadu","vauadreu","vaudeure"],
	"vaillant" => ["uaillans","uaillant","vaillans","vailliant"],
	"vaincre" => ["ueincu","vaint","veincu"],
	"vair" => ["uair","uairs","ueir","ueirs","vair","vairs"],
	"valara" => ["ualala","val","vala","valala","valara","valarara","valereu","vallereu","valleureu"],
	"valet" => ["uallet","uarlet","uaslet","vallet"],
	"valee" => ["ualee","valee","vallee"],
	"valoir" => ["uaillet","ualeis","ualoir","ualour","uaudra","uaudrai","uaut","valez","valoir","valour","valés","vaudrai","vaudroie","vauldra","vaulrai","vaurai","vaurés","vaut"],
	"valuraine" => ["ualuraine","ualuru","valuraine","valuru"],
	"vanter" => ["uante","uantent","uanter","uentent","vante","vantent"],
	"vassal" => ["vassal"],
	"veillier" => ["ueillier","ueilliés","uellier","uieillier","veillier"],
	"vendre" => ["uant","uent","vent"],
	"venir" => ["uaigne","uanra","uanrait","uendra","uendrai","uendront","ueneis","uenez","uenir","uenra","uenrai","uenus","uenuz","uenés","uiegne","uien","uient","uint","vaingne","vandra","vendra","vendrez","venez","venir","venra","venrai","venrez","venuz","viegme","viegne","viegnent","vien","viengne","viengnent","viennent","vient","vignent","vins","vint","vinz"],
	"veoir" => ["uairai","uaïr","ueoir","uerrai","uerrez","uerroie","uerré","uerrés","ueré","ueu","ueïr","ui","uoer","uoi","uoie","uoir","uois","uoit","uoy","ve","veez","veoir","verrai","verras","verray","verrez","verroie","verroye","verrés","vesrai","vez","veïr","veüe","vi","vit","voi","voie","voir","voit","voix","vouoir","voy","vé","vés"],
	"verité" => ["ueriteit","uerité","verité"],
	"vermeillete" => ["uermeillete","uermillete","uermoillette","vermeillete","vermoillete"],
	"vert" => ["uert","vers","vert"],
	"viaire" => ["uiaire","viaire"],
	"viande" => ["uiande"],
	"vie" => ["uie","vie"],
	"vierge" => ["uierge","uirge","vierge","virge","virginité"],
	"vieil" => ["uielle","uiellece","vieillece","vieses"],
	"vilain" => ["uilai","uilain","uilaine","uilaines","uilainnes","uilains","uile","uileine","uilonie","vilain","vilaine","vilaines","vilainne","vilainnes","vilains","vileine","vileines","vilenie","villain","villainez","villonie","vilonie"],
	"vile" => ["uille","vile","ville"],
	"vin" => ["uin","vin"],
	"violete" => ["uioleite","uiolete","uioletes","violete"],
	"virelai" => ["uireli","uirelis","virelai","vireli","virelin","virellai","virellin","virenli","vrelai"],
	"visage" => ["uis","uisage","vis","visage"],
	"vivre" => ["uescu","uit","uiuant","uiuerai","uiurai","uiure","uiuré","uiué","uivés","vit","viuant","viurai","viure","viuré","vivre"],
	"voer" => ["uoee","veee"],
	"voie" => ["uoie","voie"],
	"volenté" => ["uelenté","uolantei","uolanté","uolentei","uolenteis","uolenteit","uolenté","uoulentés","volenté","volentés","vollenté","voulentez"],
	"voloir" => ["ueil","ueill","ueul","ueult","ueut","uodroie","uoeil","uoil","uoill","uoille","uoldrez","uoleis","uolez","uoloie","uoloiei","uoloir","uolt","uolu","uolés","uot","uoudroie","uoudroiz","uoulez","uouloir","uueil","uueill","uueilliez","uuel","uuell","uuelt","uuet","uuil","vaudrez","vaudroie","vauroie","vaurés","veil","velt","veul","veulle","veult","veut","vodroie","voeil","voel","voiel","voil","volez","voliez","voloie","voloir","voloit","volra","volrai","volé","volés","voudrai","voudroie","voudroiz","vouldroie","voulez","vouloie","vouloir","vouroie","vueil","vueill","vueille","vueilliez","vuel","vuelt","vuet","vuil","vveil","weil","wel","welt","wil","woil"],
	"vrai" => ["uerai","ueraie","ueraiement","uoir","uoirement","urai","uraie","uraiement","urais","verai","veraie","vrai","vraie","vraiement","vraiment","vrais","vraiy","vrey", "vray"],
	"zo" => ["zo"],
	"Aiglente" => ["aiglentine"],
	"Aigline" => ["aigline"],
	"Aline" => ["alinette"],
	"Alixon" => ["alixon","alizonnete"],
	"Amelot" => ["amelot","ammelot","d'amelot","d'enmelot","emmelot"],
	"Aubert" => ["aubert","aubiert"],
	"Aude" => ["aude"],
	"Baiart" => ["baiars"],
	"Beatris" => ["beatris","beatrix","beatriz","biatris","biatriz","biautrix","bietris","bietriz"],
	"Catherine" => ["katerine"],
	"Charles" => ["charle"],
	"Clement" => ["climent"],
	"Doe" => ["doete"],
	"Doon" => ["doon"],
	"Eloi" => ["eloi"],
	"Ernaut" => ["ernalt","ernault","ernaut"],
	"Fauvel" => ["fauuel"],
	"Garin" => ["garin"],
	"Gerart" => ["gerars","gherars","gierars","girairs"],
	"Godefroi" => ["godefroi"],
	"Gui" => ["gioz","gui","guion","guiones","guionet","guionez","guiot","guioz","guis","guiz","quion"],
	"Henri" => ["henris"],
	"Hugues" => ["huwes"],
	"Jeannette" => ["iohennete","jehannete"],
	"Isabelle" => ["izabelos","ysabelos","ysabelot"],
	"Joseph" => ["joseph"],
	"Liegart" => ["liegairt","liejart"],
	"Louis" => ["loouis"],
	"Mahalot" => ["mahalot"],
	"Margot" => ["marget","margot","margueron","marguet","mergot","mergrete"],
	"Mariette" => ["mariete"],
	"Marion" => ["marion","marionete","marionnete","marions"],
	"Marot" => ["maroie","marot","marote","marotele"],
	"Mauberjon" => ["mauberions"],
	"Nicolas" => ["nicholas"],
	"Perrin" => ["perrin"],
	"Renaut" => ["raynaut","regnault","regnaut","renaut"],
	"Robert" => ["robert","robeson","robesonnet","robeçonet","robeçonnet","robeçounet","robim","robin","robinet","robins","robinés"],
	"Thierry" => ["thieris","tierri"],
	"Yolant" => ["yolanz"],
	"Agien" => ["agien"],
	"Artois" => ["d'artois"],
	"Cleresvaus" => ["cleresuaus"],
	"Ermenion" => ["d'ermenion"],
	"France" => ["france"],
	"Gien" => ["gien"],
	"Jerusalem" => ["jerusalem"],
	"Montjoie" => ["monioie"],
	"Montfort" => ["monntfort","montfort"],
	"Normandie" => ["normande"],
	"Piquigni" => ["pinquigni"],
	"Roiaumont" => ["roiaumont"],
};

$c->{reading_text_words_map} = {};
foreach my $word (keys %{$c->{reading_text_words}})
{
	#add each key word to the hash
	push @{$c->{reading_text_words_map}->{normalize('C', $word)}}, normalize('C',$word);
	foreach my $variation (@{$c->{reading_text_words}->{$word}})
	{
		#add each varient to the hash
		push @{$c->{reading_text_words_map}->{normalize('C', $variation)}}, normalize('C', $word);
	}
}


$c->{singer_blacklist} = [
"Aelis", "Amelot", "Anonyme", "Aucun (ajout du copiste)", "Aucun (citation)", "Belle Yolanz",
"Celui qui aura un cœur dévôt", "Ceux qui tardent à faire la volonté de leur dame", "Ceux qui verront la dame",
"Chantecler le coq", "Chaque âme", "David", "Des bergers", "Des bergers (st. III)",
"Des demoiselles se tenant par les mains", "Des inconnus", "Des jeunes gens et des jeunes filles",
"Des jeunes hommes à cheval, se tenant les mains deux par deux", "Deux barons", "Deux bergères (st. IV)",
"Deux compagnons", "Deux jeunes filles (st. I)", "Deux jeunes hommes", "Deux neveux du comte de Dinant",
"Dieu", "Emmelot", "Esther", "Garnier, l'ami de la bergère", "Gui", "Gui (st. I-II/IV)", "Guiot", "Imprécisé",
"Inconnu (le refrain est le premier vers d'un folio qui suit un folio manquant)", "L'amant", "L'amant potentiel",
"L'ami", "L'ami de Dieu", "L'ami de Marot (refrain final)", "L'amie du marié", "L'assemblée des danseurs",
"L'auteur", "L'auteur (st. I-IV)", "L'auteur (st. II)", "L'auteur (st. II/IV-VI)", "L'auteur (st. III/V)",
"L'auteur (st. V)", "L'auteur (st. VI)", "L'auteur et ses amis", "L'auteur et ses lecteurs", "L'auteur et une bergère",
"L'auteur et une compagne anonyme", "L'auteur ou l'ami de la dame", "L'auteur ou le copiste", "L'auteur-amoureux",
"L'auteur-héros", "L'auteure", "L'auteure (st. I)", "L'aînée des sœurs", "L'Église", "L'âme", "L'âme heureuse",
"L'âme égarée", "L'épouse", "La belle Aye", "La bergère (st. I)", "La chanson", "La compagnie", "La comtesse",
"La dame", "La dame (st. V)", "La fille d'en Hue", "La jeune fille qui lira l'œuvre", "La mère de la bergère (st. IV)",
"Le bon amoureux", "Le bon chanteur", "Le cœur amoureux", "Les acteurs du charivari", "Les amis du vilain",
"Les amoureux", "Les anges", "Les bons chanteurs", "Les compagnons de l'auteur", "Les cœurs amoureux", "Les dames",
"Les dames amoureuses depuis longtemps, découvrant un nouvel amour", "Les dames mariées", "Les demoiselles",
"Les femmes", "Les jouvenceaux", "Les jouvenceaux amoureux", "Les maris", "Les martyrs", "Les nonnes",
"Les sages jouvenceaux", "Les trompeurs", "Les vaillants amoureux", "Marot", "Marot (st. V)", "Marotele",
"Perrin (st. V)", "Phebus", "Son ami (st. IV)", "Un amoureux", "Un berger", "Un berger (Gui)", "Un berger (Robin)",
"Un chevalier", "Un jeune homme", "Un messager", "Un messager ?", "Un poète, cité par l'auteur",
"Un valet du comte de Spire", "Une belle", "Une bergère", "Une bergère (st. I)", "Une bergère (st. I-II)",
"Une bergère (st. I-IV)", "Une bergère (st. I/III/envoi)", "Une brunette", "Une dame", "Une dame (st. VI)",
"Une demoiselle", "Une des sœurs", "Une félonne", "Une jeune fille", "Une jeune fille (st. I-III)",
"Une jeune fille et son ami (st. V)", "Une jeune nonne", "Une voix", "« Celui qui cest refrait chanta »",
"« Celui qui chanta cest motet » (refrain-citation)", "« Cil qui dist »", "« Cui qui poit »", "« La belle »",
"« Le bon chanteur »", "« Les autres »", "« On » (refrain-citation)","« Celui qui chanta cest motet » (citation)",
"« Cil qui dist » (citation)","« On » (citation)", "« cius qui bien vos puist dire » (citation)"
];

$c->{singer_blacklist_hash} = {};
foreach my $word (@{$c->{singer_blacklist}})
{
	$c->{singer_blacklist_hash}->{normalize('C', $word)} = 1; 
}



$c->{generic_descriptor_blacklist} = [
"Refrain",
"Bestiaire","Chronique","Conte pieux","Correspondance","Débat strophique","Dit","Dit allégorique","Dit allégorique strophique","Dit strophique",
"Fabliau","Fatras","Miracle de la Vierge","Miracles illustrant les propriétés des choses","Motet farci?","Œuvre didactique","Poème allégorique",
"Poème en forme de débat","Poème épique","Poème narratif","Poème narratif strophique","Poème strophique","Probatio pennæ","Recueil de citations",
"Recueil de miracles de la Vierge","Recueil de proverbes","Rêverie","Sermon","Salut d'amour","Théâtre","Traduction-adaptation de l'Ars amatoria d'Ovide",
"Traduction-adaptation du cantique des Cantiques","Traité spirituel","Traité sur l'amour"
];

$c->{generic_descriptor_blacklist_hash} = {};
foreach my $word (@{$c->{generic_descriptor_blacklist}})
{
	$c->{generic_descriptor_blacklist_hash}->{lc(normalize('C', $word))} = 1; 
}

$c->{generic_descriptor_words} = 
{
	"Chanson" => ["Ballade avec des refrains","Ballade à refrain","Ballette avec des refrains","Ballette à refrain","Ballette à refrain et refrain interne","Chanson","Chanson avec des refrains","Chanson avec des refrains et refrain interne","Chanson balladée","Chanson balladée à refrain","Chanson d'aube à refrain","Chanson de mal mariée avec des refrains","Chanson de toile à refrain","Chanson à refrain","Chanson à refrain bilingue","Chanson à refrain et refrain interne","Chanson à refrain et refrains internes","Chanson à refrain interne","Descort","Estampie à refrain","Pastourelle","Pastourelle avec des refrains","Pastourelle avec des refrains et refrain interne","Pastourelle à refrain","Pastourelle à refrain et refrain interne","Pastourelle à refrain interne","Pastourelle à refrains internes","Reverdie à refrain","Rotruenge à refrain","Rotruenge à refrain interne","Serventois à refrain","Virelai"],
	"Clausula" => [],
	"Motet" => ["Motet","Motet enté","Motet-centon","Motet-refrain","Rondeau-motet", "Motet?"],
	"Organum" => [],
	"Rondeau" => ["Rondeau","Rondeau strophique","Rondet","Rondet strophique"],
	"Roman" => ["Roman","Roman allégorique","Roman d'aventures"],
};


$c->{generic_descriptor_words_map} = {};
foreach my $word (keys %{$c->{generic_descriptor_words}})
{
	#add each key word to the hash
	push @{$c->{generic_descriptor_words_map}->{lc(normalize('C', $word))}}, normalize('C',$word);
	foreach my $variation (@{$c->{generic_descriptor_words}->{$word}})
	{
		#add each varient to the hash
		push @{$c->{generic_descriptor_words_map}->{lc(normalize('C', $variation))}}, normalize('C', $word);
	}
}
