use Unicode::Normalize 'normalize';
use utf8;

$c->{reading_text_stop_words_list} = [
"defferrés","deuotemet","puisqu'il",
"mescheance","mescheans","mescheanz","meschief","mescreance",
"qu'an",

"0","a","ab","ac","aclergis","ad","adiuua","adons","adorant","adrez",
"aduocatrix","agamus","age","agnus","ai","aie","aient","aies","aiez","aiiés",
"aijés","aillors","aillours","aincor","ait","aié","aiés","al","allors","allours",
"almus","am","amabilis","amone","amoris","amploiee","an","ancor","ancores","anfor",
"angeles","angelis","angelorum","aniex","anploiee","aperit","aprés","ar","ara","arai",
"ardoir","arez","argent","ariere","arieres","aroi","aroie","aroit","aroye","ars",
"artium","arés","as","asouueÿr","asprement","asprete","asralié","asseis","assez","asés",
"at","atalente","atraiance","atraire","atrium","au","aual","auan","auance","auant",
"auc","aucuns","audi","aue","auec","aueir","aueiz","aueoir","aueques","auerai",
"aueroie","aueuc","aueucke","auez","aul","auoc","auoec","auoie","auoir","auoit",
"aura","aurai","auray","aurei","aureis","aurez","auroi","auroie","auroiz","aurons",
"aurés","aus","ausi","ausint","aussi","aut","autant","autem","autre","autrement",
"autres","autresi","autrui","auuec","auugle","aux","aué","aués","av","avantaige",
"ave","avecques","averai","aver","aveuc","aveuckes","aveugle","avez","avoec","avoeques",
"avoir","avé","avés","ay","ayt","b","bait","barat","bas","beatis",
"bec","bee","bei","beit","benedicamus","bet","bethlehem","bien","bin","bis",
"biuonetz","bjen","bobance","bonas","boqe","bordon","boucher","bouchier","bouqe","brauium",
"brief","briez","bruit","buef","buer","bure","c","c'a","c'ai","c'ains",
"c'ainz","c'an","c'apeirt","c'au","c'aurai","c'autre","c'autrement","c'autres","c'ele","c'elle",
"c'en","c'es","c'est","c'il","c'om","c'on","c'oncore","c'onqes","c'onques","c'or",
"c'ore","c'un","c'une","cai","can","canque","capit","car","carcere","caritas",
"carne","carneam","castitas","ce","cel","cele","celebrem","celestium","celi","celicum",
"celle","cellui","celluy","celly","cels","celui","cembel","ceo","cera","cert",
"certaine","certeine","certeinement","certes","ces","cest","ceste","cetera","ceu","cha",
"chaciés","chainse","chaloir","chamin","char","chasteé","chat","che","chele","cheli",
"cher","chest","cheste","chi","chien","chier","chiere","chil","chix","chou",
"ci","cil","cilz","cis","cist","cité","ciuiere","cius","ciz","cjs",
"cloroit","clorroit","cognissance","cognitas","cognoist","coi","coins","colee","com","combat",
"come","coment","comme","comment","commere","comprendre","comun","con","conferme","confermet",
"confert","confertur","confonde","conme","conment","connoist","conoist","conplainte","conroi","consaut",
"conseil","conseilliés","consent","conseut","consirer","consoit","conte","contraire","contratendant","contre",
"conuertentem","copia","corde","cordibus","cordis","cornettes","corrouz","cort","couant","couchai",
"couchier","coudroie","couille","coulle","coument","counoist","coup","coupe","couppe","courroucier",
"courrucié","courte","cousu","couuerture","coux","cras","creature","crere","crescens","crigne",
"crine","crinne","croissent","croix","crollet","cruce","cu","cude","cui","cul",
"cullir","cum","cur","cure","currencium","cy","d'a","d'ambedeux","d'ame","d'anbedeux",
"d'argent","d'arme","d'armes","d'assez","d'assés","d'atrui","d'auenir","d'aultrui","d'auoir","d'aus",
"d'autel","d'autre","d'autretel","d'autrui","d'avoir","d'awan","d'elegier","d'enfern","d'eschiueir","d'estre",
"d'esté","d'ire","d'ortie","d'ou","d'outre","d'outremer","d'un","d'une","d'vn","da",
"dahait","dahez","dains","dairt","dam","damnés","dampnés","dan","dant","danz",
"dar","dart","das","dat","datis","datur","de","dearragié","debitas","dechaciés",
"decus","dedaignouze","dedens","dedit","defaus","defaut","defaute","defera","defferés","deffie",
"defrit","degraz","degré","dehait","dehaiz","dei","deificum","del","delaie","deleuit",
"demie","denié","dens","dent","denz","deo","deprecare","deques","derora","des",
"desere","desfie","desfié","deshait","desloie","desous","desouz","despansans","despeit","despice",
"despit","desproué","dessouz","dessus","destinee","destiné","destoupeit","destresse","destroit","desuestus",
"desus","desvestus","detre","detri","deuant","deuis","deuise","deuize","deum","deuorés",
"deuotement","deuotemt","deuoto","devise","dez","dicite","dictas","dictes","die","digna",
"diversent","doble","dobleir","dobler","doblera","doces","doctrine","domine","domino","donc",
"doncques","donques","dongier","dongiers","dons","dont","dor","dotain","dotance","dou",
"doubler","doublera","dout","doutance","doute","draps","drincheyl","du","duc","duce",
"dulcissima","dune","dunt","dusqu'a","dusques","dux","d'aultrui","d'avoir","d'elegier","d'estre",
"e","ea","eage","eai","eaige","eclesie","eest","eeue","egypte","ei",
"einsi","einsin","einsint","einssi","eis","eit","el","ele","eles","elle",
"elles","ellire","emanuel","embrace","empetrez","emprendre","emprent","emprisonés","en","encliné",
"encontre","encor","encore","encores","encousue","endroit","enfuie","enganez","enganés","engignié",
"enhaï","enla","enmuree","enploiee","enragie","enrichis","enrragiez","ens","enseueli","ensi",
"ensient","enssi","ent","ente","entient","entier","entiere","entieremant","entire","entre",
"entremectre","entremettre","entsi","enuaï","enuers","eos","ere","eripit","erré","errés",
"ert","es","escheuie","eschiuee","escient","escorchier","escïent","eslaceer","eslire","esmai",
"esmerueille","esploit","esploita","espousera","espuee","espé","esragie","essin","est","estable",
"estaindre","estei","esteis","ester","estes","estient","estincele","estoet","estoit","estre",
"esté","et","eu","euc","euch","eue","eve","ex","exenplario","exilio",
"exordium","extremitas","ez","eü","eür","eüsse","fa","fac","face","facent",
"fach","fache","faciez","faciés","facta","faet","fai","faic","faice","faictes",
"faire","fais","faisans","fait","faite","faites","faiz","fareis","fas","fascia",
"fate","fault","fay","faz","façon","fecunda","feire","feit","fer","fera",
"ferai","ferait","ferat","feray","fere","fereis","ferez","feriés","feroie","ferois",
"feroit","ferons","feront","ferret","feruida","ferunt","feré","fes","fet","fetes",
"feur","feïs","feïsse","feïst","fiance","fichera","ficherai","fide","fie","fiel",
"fier","fierete","fiez","figat","figit","figure","fil","filer","filg","filio",
"filium","fis","fist","fit","fius","foire","fois","foix","fonde","fons",
"font","for","force","forche","forestier","forfet","formant","forment","fors","fort",
"fos","foue","foule","fourestier","fourfaisans","fourré","fours","françois","frese","frestele",
"frigandés","froiches","fruens","fu","fuer","fui","fuians","fuiez","fuison","fuissent",
"fuissiés","fuisti","fuit","fuiés","fus","fuse","fusiez","fusse","fussent","fussiez",
"fussiés","fust","fut","futurum","fuy","fycherai","g","g'en","g'ere","g'i",
"g'ier","g'iere","g'ié","g'é","gaaigneroit","gaber","gabriel","gaigneroit","gaillarde","gaires",
"gairt","gaite","gaitent","gaiteurs","game","garni","gars","gart","gas","gastee",
"gaterés","gaudia","gaudium","gauz","ge","gedeonis","gehir","gemina","gemineo","genitoris",
"genitrix","genous","genoz","germani","geronnees","ges","geter","geu","giganti","gillette",
"girodele","girondele","gironees","gironnees","gitez","glacier","glai","glaiolais","gloire","gloria",
"glorie","glorificum","gloriosa","gorpiz","goustez","goustés","goy","graci","gracias","graile",
"grain","grano","granum","gras","guas","gueires","gueiteurs","guere","guerre","guerroie",
"guerroier","guete","guise","guisse","gute","ha","habet","habitas","hachie","haire",
"halete","hallee","han","hardi","hart","has","haschie","haste","hastis","hastés",
"hellequin","hemne","herbages","herbaige","hi","ho","hoc","hodie","hokes","hominem",
"hors","hostia","hous","housiaus","houx","houziaus","hoziaus","humés","hure","hurta",
"i","i'a","i'abaterai","i'ai","i'aie","i'an","i'arai","i'auerai","i'auoie","i'aurai",
"i'avoir","i'ay","i'ei","i'en","i'ere","i'estoie","i'é","ia","iai","iaus",
"icel","icele","icels","icest","ichi","ici","icy","id","ie","iehir",
"iel","ier","iere","iert","ierusalem","iestes","iestre","igne","ignem","igni",
"il","illi","illuminans","im","immolatus","in","induco","induit","ine","inficiunt",
"io","iou","iouster","ioute","ire","israhel","issi","istra","istre","iu",
"iubilo","iudaice","iugement","iui","iuijs","ius","iusque","iusques","iustise","iustum",
"j","j'a","j'ai","j'aie","j'an","j'arai","j'aurai","j'ay","j'aye","j'en",
"j'ere","j'ey","ja","jai","jairt","jangleos","janglerie","jardinet","jay","je",
"jen","jeo","jl","jo","jou","jre","ju","jugement","jus","jusques",
"jv","k'a","k'ainc","k'ains","k'ainz","k'an","k'assés","k'au","k'auoc","k'auoie",
"k'autre","k'autres","k'autresi","k'ele","k'elle","k'elles","k'en","k'ensi","k'il","kai",
"kan","kank'il","kant","kar","ke","keil","kerre","kes","ki","kiconques",
"koi","l","l'a","l'abe","l'ai","l'aie","l'ait","l'ame","l'an","l'ante",
"l'arai","l'arbre","l'aube","l'auera","l'auiés","l'auoir","l'auoit","l'aura","l'aurai","l'auray",
"l'auré","l'autre","l'autrier","l'aviés","l'avoir","l'avoirs","l'ay","l'eez","l'eglise","l'eglyse",
"l'en","l'escot","l'est","l'eue","l'i","l'oliuier","l'om","l'on","l'ore","l'ot",
"l'uns","l'é","la","laborer","lace","lai","laice","laide","laisette","lance",
"lanche","larges","larmes","laron","larron","larrons","las","lasse","lassete","lassette",
"latuit","laudare","laudor","laus","le","leis","lente","lepra","lermer","lermes",
"les","lesçun","leticia","leticie","leuchet","leui","leur","lex","lez","li",
"lie","ligaf","ligat","liges","ligier","lille","lire","lis","lit","liura",
"liurés","liz","lj","locum","logemt","loire","loiriete","loirion","loisir","lor",
"lors","losangier","losenger","losengier","lou","lour","lucis","lui","luist","lundi",
"lupinele","ly","lés","m","m'a","m'afebloie","m'aie","m'aigrie","m'ais","m'ait",
"m'ame","m'amistié","m'an","m'ara","m'arés","m'asseür","m'at","m'atalent","m'atalente","m'aueis",
"m'auez","m'auoit","m'aura","m'aurait","m'aureis","m'aués","m'aveis","m'avez","m'avés","m'en",
"m'enbelist","m'ent","m'entente","m'ert","m'esmai","m'esprent","m'est","m'ester","m'estes","m'eut",
"m'i","m'iert","m'on","m'ont","m'ot","m'out","m'y","ma","magrei","mai",
"maig","maintenant","mainz","maire","mais","maisele","maison","maissele","maistrie","maix",
"maiz","malauisés","malgrei","malgré","malle","malmenant","malois","maloit","malparliere","maltalent",
"malum","manche","manes","manie","manierette","manoir","mar","mare","maria","marrit",
"mars","martire","marz","mas","mater","matons","maudahait","maudehait","maugré","mautalent",
"mauvoir","may","me","mehaigne","mei","meilleur","meillor","meillors","meillour","meillours",
"meint","melius","melz","memes","men","mençoigne","mer","meri","merita","merri",
"meruail","meruaille","mes","mesauenir","meschant","mescine","meserrez","mesire","mespensans","messire",
"mestre","mestres","mestrie","meuz","mey","meyre","mez","mi","miaus","miauz",
"mie","miels","mielz","mien","miens","mies","mieudre","mieulx","mieus","mieux",
"mieuz","miex","miez","millor","millour","millours","mins","miols","mire","miserie",
"mitis","mius","mix","mocke","moi","moie","moies","moins","mois","moitié",
"moke","mokiés","moles","molt","mon","monter","moquez","moquiés","moribus","morrie",
"mortificata","morum","moult","mout","moy","mu","muciez","muciés","mue","muedre",
"muels","muelz","muere","mues","muez","muguet","mulier","mulierum","mult","mun",
"mundane","mundi","mundoque","mundum","mus","my","mé","més","n","n'a",
"n'ai","n'aie","n'ait","n'aiés","n'an","n'aproche","n'aprochiez","n'ara","n'aroie","n'aroit",
"n'assentez","n'at","n'auarat","n'auera","n'auerai","n'aueroie","n'auez","n'aura","n'aurai","n'aurait",
"n'auray","n'aurez","n'auriez","n'auroie","n'auroit","n'aurés","n'aués","n'ay","n'ayt","n'ele",
"n'elle","n'em","n'en","n'encor","n'enport","n'enquore","n'ensaiera","n'ent","n'ere","n'ert",
"n'es","n'est","n'et","n'eut","n'ey","n'eüxe","n'i","n'iere","n'iert","n'istrai",
"n'o","n'oi","n'oncor","n'onkes","n'onques","n'ont","n'ot","n'uevre","n'unques","n'y",
"n'yerent","n'é","na","nacio","naie","naist","nam","nanil","natio","nature",
"natus","ne","neant","nee","neient","neiz","nel","nenil","nennil","neporcant",
"nes","nete","neu","ni","niant","nient","nil","nimphe","nis","nit",
"nititur","no","nobilitas","nobis","noiant","noient","noire","nois","nomen","non",
"nonpor","nonporcant","nos","nostra","nostre","nostris","nou","nous","noz","noël",
"nube","nuc","nue","nuef","nul","nule","nullam","nulle","nullui","nuls",
"nului","nulz","nunc","nuncius","nuns","nunz","nus","nuz","nuzlui","nvs",
"néo","o","oan","od","oi","oltree","om","omnis","omnium","on",
"onan","oncor","oncore","oncques","onkes","onqe","onqes","onques","onquez","onquor",
"ont","operis","or","ora","orandroit","ordenez","ordenés","ordines","ore","orendroit",
"ores","ori","oris","ornata","ortie","ortus","ot","ou","ouec","ourlé",
"out","outrageus","outre","outree","outreement","ouurier","ov","oé","p","pa",
"pace","paee","paie","paiera","pain","pais","palerin","papelart","par","parem",
"parfais","parfaite","parfaitement","parfete","paris","parix","parmi","pas","pater","patri",
"patrie","patrium","patruum","peccati","peccatum","pecche","pechié","pecunia","peir","peires",
"pelerim","pelerin","peliçon","per","perceus","pere","peril","pernez","perpetuo","perpetuum",
"personis","pessue","pestri","pestris","peu","peux","pex","pez","pia","piau",
"pickenpot","pickentpot","pieau","piecea","pieu","pieux","pieça","piis","pikempot","plai",
"plaie","pikenpot","pinkenpot","piour","pire","pis","pié","piés","plaie","plano",
"plevis","pluie","plus","plust","plux","pluz","po","poinnes","pointure","poise",
"poissance","poissans","poitrine","poize","pol","ponce","por","porcant","porchier","porqant",
"possimus","pou","pouc","poul","pour","pourquoy","poursieuroit","poursuiuroit","poynt","praelet",
"pramesse","precum","prelaz","pres","presidium","pressuris","prestat","pretancium","preuost","prevoust",
"prez","pries","prima","primez","principaument","priué","priveté","pro","prodest","proesce",
"proesse","prou","prouidence","pu","puce","pues","puis","pusqu'il","puisque","pur",
"pure","put","pvis","q'a","q'ai","q'an","q'au","q'autre","q'autresi","q'en",
"q'il","q'om","q'un","qanqe","qanqu'il","qanque","qant","qar","qe","qel",
"qi","qoi","qu'a","qu'adés","qu'ai","qu'aie","qu'ainc","qu'assez","qu'au","qu'auerai",
"qu'auoie","qu'auoir","qu'aurai","qu'ausi","qu'autre","qu'avons","qu'ay","qu'aye","qu'el","qu'ele",
"qu'eles","qu'elle","qu'en","qu'entre","qu'est","qu'ieu","qu'il","qu'oi","qu'or","quam",
"quan","quand","quanqe","quanque","quanques","quant","quar","quasser","que","quel",
"quellir","quem","quens","queque","queris","queus","queux","quex","qui","quiconques",
"quil","quin","quit","quo","quoi","quoquillete","quoy","qvant","qve","qvel",
"qvi","r","rai","raist","ranfuzeit","rape","rauerai","raui","rauoit","raurai",
"reatus","rechoit","reclamer","recoumandons","redimes","redimitas","redout","redoute","refais","regina",
"regna","regnare","regnat","regnum","regretot","releuauit","relicta","reliqum","reluisoit","remedium",
"remontés","remue","remuer","remué","renardie","reniast","renoie","repaire","reperitur","requie",
"resort","resours","resourz","respice","respit","respuns","restituitur","retaudrai","retour","retraire",
"reuel","reuerdir","reuertatur","reuiendo","rex","reçoit","rien","riens","rienz","riredure",
"riuaige","rius","robe","rogamus","roi","rois","roissoles","romanz","ronc","rosine",
"rous","roy","rue","s'a","s'ai","s'ainkes","s'ainques","s'aipert","s'alme","s'alongera",
"s'ame","s'an","s'apert","s'arai","s'aucun","s'auerons","s'auilenist","s'auilonist","s'aura","s'aurai",
"s'auray","s'aureis","s'auriés","s'auroiz","s'aurés","s'autrement","s'avrai","s'ay","s'el","s'ele",
"s'elle","s'en","s'enfuie","s'ensi","s'entente","s'est","s'i","s'iere","s'iert","s'il",
"s'on","s'onkes","s'onques","sa","sacrario","sacrificata","salua","saluari","salutis","san",
"sanctorum","sanguine","sans","santé","sanz","saous","sarasin","sarrasin","sarrazin","sautele",
"scitis","se","seant","seculo","seculum","sed","seez","sei","seli","sella",
"selonc","semer","seminans","semont","senee","sensilis","sentele","sepmaines","sequere","sera",
"serai","seray","seri","seroi","seroie","seroit","serray","seré","ses","seu",
"seue","seur","seure","seus","seux","sez","seürement","seürté","si","sicles",
"siecle","siecles","siegle","sien","siens","sienz","siet","silz","sine","sis",
"sit","sith","soc","soeif","soi","soie","soient","soiez","soir","soit",
"soiés","sol","soliers","som","sommes","son","sonerait","sont","sor","sou",
"souant","soue","soueif","souent","souerain","sougis","souhaidier","souine","soupe","souppe",
"sour","sourt","sous","souuent","souz","soweif","soweit","soy","soz","speciosa",
"speculum","spem","spes","stadium","stola","su","sua","subsidia","sue","suer",
"suffragia","sui","suis","suix","suiz","sun","sunamitis","sunt","suos","super",
"supplicancium","sur","surgens","sus","suy","suz","sy","synaï","t","t'ai",
"t'en","t'est","ta","tabair","tabairt","tabar","tailler","taillier","tair","tairt",
"taisir","tal","talant","talens","talent","tamprement","tannt","tanrement","tant","taprement",
"tarza","taunt","taut","te","tedium","teil","teile","teille","teire","tel",
"tele","teles","telle","teltes","telz","temprement","tendo","tenebris","teritur","termes",
"termino","tes","teu","teus","tey","tez","thronis","tier","tieux","tiex",
"tir","toi","ton","tor","tormentis","tors","tort","torta","tos","tost",
"tostans","tot","tote","totz","toudis","touiours","toujours","tour","touriours","tours",
"tous","tout","toute","toutes","touz","toz","trabeam","trace","trage","trahat",
"tramiti","trepe","tres","trestous","trestout","trestoute","trestoz","trestuit","tretous","trez",
"tribua","tribus","trino","trinum","tripicum","triticum","trop","trot","trés","tu",
"tua","tui","tuit","tum","tuum","tuz","tés","u","ubi","uenge",
"ueniam","uenie","uer","uerbum","uere","uers","uert","uertu","uerz","uesci",
"uespres","ueteres","uez","uia","uias","uicijs","uif","uim","uirgo","uita",
"uitam","uitas","uite","uitiis","uitijs","uitis","ultimum","umbre","un","une",
"unico","unitas","unitrino","uno","uns","unum","uo","uocauit","uoces","uocis",
"uoice","uolaige","uolentiers","uorrai","uorsai","uos","uostre","uostres","uou","uoulentiers",
"uous","uoustre","uouz","uox","uoz","ut","uus","ué","v","vale",
"valer","vatendo","vesci","veo","vertus","vestu","via","vias","vic","victoria",
"vif","vilai","vitas","vite","vn","vne","vnes","vng","vngs","vnques",
"vns","vo","volant","vole","volentiers","vorrai","vos","vostre","vostres","voulentiers",
"vous","vouz","voz","vus","werpir","wesseyl","xorderie","xort","y","ycy",
"yessea","ç'ai","ça","çou"
];

$c->{reading_text_stop_words_hash} = {};
foreach my $stop_word (@{$c->{reading_text_stop_words_list}})
{
	$c->{reading_text_stop_words_hash}->{normalize('C', $stop_word)} = 1; 
}


$c->{reading_text_words} = {
	"abandoner" => ["abandoner","abandon","abandonai","abandonnai","abandouné","bandon"],
	"achater" => ["achater","acater","achater","acheter","akater"],
	"acomplir" => ["acomplir","acomplie","aconplie"],
	"acointer" => ["acointer","l'acointai","m'acointa"],
	"acoler" => ["acoler","acoleis","acolez","acolés"],
	"acueil" => ["acueil","acueil","acuil","agoill"],
	"adando" => ["adando","adando"],
	"ades" => ["ades","adiés","adés"],
	"adieu" => ["adieu","adieu"],
	"adroit" => ["adroit","adroit"],
	"ae" => ["ae","ae","aé","aéo","aéu","éo"],
	"afaire" => ["afaire","afaire"],
	"afier" => ["afier","afieit","afiert"],
	"afoler" => ["afoler","m'afolera"],
	"agace" => ["agace","agace"],
	"agneau" => ["agneau","agniel","aignel","aigniel"],
	"agreer" => ["agreer","agree","m'agree"],
	"ahi" => ["ahi","ahai","ahi","ahie","ay","aï","haÿ"],
	"aide" => ["aide","ayde","aïe","s'aïe"],
	"aider" => ["aider","aiderés","aidier","aidiez","aidiés","m'aide","m'aiudar","m'aïst","m'aït","m'aÿt"],
	"aimi" => ["aimi","aimi","aimmi","ainmi","ajmmi","aymi","eimi","emi","emmi","enmi","eymmi","hemi","k'ainmi"],
	"ainc" => ["ainc","ainc","ains","ainz"],
	"ainsi" => ["ainsi","ainsi","ainsin","ainsint","ainsit","ainssi","ajnsi","ansi","ançois"],
	"alatire" => ["alatire","alatire"],
	"alegement" => ["alegement","alegement","aligement","d'alegement","n'alegement"],
	"alegier" => ["alegier","alegier","alegiez","alegiés","aligiez","allegiez","d'alegier","d'alleger","m’aliege","m'aligest","ralegiés"],
	"aler" => ["aler","aleir","aleis","aler","alez","alleis","aller","allez","aloie","alons","alé","alés","g'irai","i'aille","irai","irat","ireis","irez","irés","m'irai","n'aille","n'alez","n'alés","n'ira","n'iroie","n'iront","n'irés","s'alleis","ua","uait","uas","uat","uet","uoix","uont","va","vait","vas","vois","voise","voist","voix","voiz","vont","ralons","reuois"],
	"aleuriva" => ["aleuriva","aleuriua","aleuryua","luriua"],
	"all" => ["all","all"],
	"aloete" => ["aloete","aloete","l'aloete","l'alowette","loete"],
	"alumer" => ["alumer","aluire","aluirer","alume","alumer","alumé"],
	"amant" => ["amant","amans","amant","amanz","amaunz"],
	"amendement" => ["amendement","amendement"],
	"amender" => ["amender","amandeir","amander","amender"],
	"amener" => ["amener","amaine","anmoinnent","enmaigne","enmaine","l'amaine","l'enmoinrés","m'amaine","m'amenez","t'amaint"],
	"amer" => ["amer","aiinz","aim","aime","aimeroit","aimme","aimé","ain","aing","ainme","ainment","ainmet","aint","ama","amai","amee","amei","ameie","ameir","ameis","ameit","amer","amera","amerai","amerait","ameras","ameray","amerez","ameroie","ameroit","ameré","amerés","amet","amez","amoit","amons","amé","amés","anamer","armer","ayme","c'ameir","d'ameir","d'amer","d'amier","d'ammer","entreamez","i'aim","i'aime","i'ain","i'ainc","i'aing","i'ainme","i'ains","i'am","i'amaixe","i'amasse","i'amerai","i'amoie","i'ayme","j'aim","j'aime","j'ain","j'ainc","j'aing","j'ains","j'am","j'amaisse","j'amera","j'amerai","j'ayme","k'amaie","k'amee","k'ameie","l'aim","l'aime","l'aimme","l'ain","l'ainc","l'aing","l'ainme","l'aint","l'ameir","l'ameis","l'amer","l'amerai","l'ameroi","m'aime","m'aimes","m'aimme","m'aimmes","m'aimmet","m'ainme","m'aint","m'ama","m'amas","m'amera","m'amerait","m'amerat","m'amerez","m'amez","m'amoit","m'amé","m'amés","m'eime","n'aim","n'aime","n'aimme","n'ain","n'aing","n'ainme","n'ama","n'amai","n'amer","n'amera","n'amerai","n'amerais","n'ameroie","n'ameré","n'amez","n'amoie","n'amés","q'amer","qu'amee","qu'amer","qv'amee","s'aim","s'aimme","s'ain","s'aing","s'amera","s'amerai","s'ameray","s'ameroi","s'amerons","s'amorai","s'antraimme","s'antraimmet","s'antreimmet","t'aim","t'ain"],
	"ami" => ["ami","ami","amie","amiet","amiete","amiette","amin","amins","amis","amiz","amj","amy","c'amis","cank'amis","d'ami","d'amie","d'amiete","d'amin","l'ami","l'amin","m'amiate","m'amie","m'amiete","n'amie","s'amie","t'amie"],
	"amor" => ["amor","aamors","amoir","amor","amors","amour","amours","amourz","amous","amur","amurs","bon'amor","c'amors","c'amours","d'amor","d'amors","d'amour","d'amours","d'amur","d'amurs","d'amourz","k'amors","k'amours","l'amor","l'amour","m'amor","m'amors","m'amour","m'amur","malamour","q'amors","q'amours","qu'amors","qu'amours","s'amor","s'amors","s'amour","s'amours"],
	"amorete" => ["amorete","amorates","amorestes","amorete","amoretes","amorette","amorettes","amourectes","amoureite","amoureites","amourete","amouretes","amouretez","amourette","amourettes","amourettez","d'amoreites","d'amoretes","d'amorettes","d'amoureites","d'amourete","d'amouretes","d'amourettes","k'amorettes","qu'amouretes"],
	"amoreus" => ["amoreus","amerous","amerouse","amerouzés","amoraz","amoros","amorose","amorous","amourat","amorous","amourat","amourez","amouros","amourous","amouré","amourés","enamoree","enamourat","enamouré"],
	"amoreusement" => ["amoreusement","amerousemant","amerousement","amerouzement","amoreusement","amoureusemant","amourousement"],
	"anel" => ["anel","l'anelet","l'anelez"],
	"anui" => ["anui","annuj","annuy","anoie","anui","anuye","d'ennui","ennuie","ennuit","ennuy","ennuye","m'enoye"],
	"anuit" => ["anuit","aneut","annuit","anuit"],
	"apercevoir" => ["apercevoir","aperceuoir","parsue"],
	"apeler" => ["apeler","apele","apeler","apelleir","i'apelerai","j'apelerai","j'apielerai","j'appellerai","m'apele","m'apelle"],
	"aporter" => ["aporter","aporta","apourta"],
	"aprendre" => ["aprendre","aprendera","aprendés","apreneis","aprenez","aprennez","aprent","aprins","apris","s'aprendeis"],
	"assaillir" => ["assaillir","m'asaut","m'assaut"],
	"assaut" => ["assaut","assault","assaulx"],
	"assavorer" => ["assavorer","asauoré","asauoreit","asauouré"],
	"assener" => ["assener","assegné","assenee","assenés"],
	"asseoir" => ["asseoir","asise","assis","assiz","ceant","m'assis","seant"],
	"assoagier" => ["assoagier","m'aisuaige","m'asoage","m'asoaige","m'asoshaige","m'asouage","m'assoage","m'assouage","n'assouaige"],
	"ataindre" => ["ataindre","ataindre","ataint"],
	"atendre" => ["atendre","atandrai","atandre","atant","atench","atendance","atendant","atendoie","atendrai","atendre","atens","atent","attens","attent","i'aitent","i'atandoie","i'atant","i'atemps","i'aten","i'atenc","i'atenderai","i'atendoie","i'atendrai","i'atendroie","i'atent","j'atant","j'atendrai","j'attendrai","k'atent","l'atendrai","m'atant","m'atendeis","m'atent","n'atenc","n'atent","qu'atent","ratendez","ratendés","s'atant","s'atent"],
	"aunoi" => ["aunoi","l'annoi","l'anoi","l'anoy","l'aunai","l'aunoi"],
	"avalabondenne" => ["avalabondenne","aua","avalabondenne"],
	"avenant" => ["avenant","auenant","auenanz"],
	"avenir" => ["avenir","aduenir","auaigne","aueigne","aueinne","auenir","auenoit","auiegne","auieigne","auiengne","auient","auignet","aviegne"],
	"aventure" => ["aventure","auanture","auenture","aventure"],
	"bacheler" => ["bacheler","bacelers","bacheleir","bacheler","bachelers"],
	"baillie" => ["baillie","bailie","ballie","baillie","balaie"],
	"baillier" => ["baillier","baille","bailler","bailli","baillier","baillir"],
	"baiselete" => ["baiselete","baicelete","baicelette","baiselete","baisselete","besselete","boisselete"],
	"baisier" => ["baisier","baiser","baisier","baisiez","baisiés","baixiés","beisiez","besera","besiez","besiés"],
	"baler" => ["baler","bal","bale","baler","balera","balerie","balez","balleir","ballerie","balés"],
	"baron" => ["baron","baron"],
	"batre" => ["batre","bait","bat","bateis","batera","baterat","batez","batra","batue","batés"],
	"baudor" => ["baudor","baudor","baudour","baudur"],
	"beguin" => ["beguin","begine","beguin","beguineite"],
	"bel" => ["bel","baut","beau","beaus","beaux","beax","bel","bele","bella","belle","bias","biau","biaul","biaus","biaux","biauz","biax","biaz","biel","biele","bielle","bjau"],
	"belement" => ["belement","belemant","bellemant","bellement","bielement"],
	"bergerete" => ["bergerete","bargeronette","bargerounette","bergerete","bergeronete","bergeronnete","bergeronnette","bregeronete"],
	"biauté" => ["biauté","beautez","biautei","biauteit","biautez","biauté","biautés"],
	"biens" => ["biens","biens"],
	"blanc" => ["blanc","blanc","blanque","blant"],
	"blasmer" => ["blasmer","blameis","blamer","blamez","blamés","blasmee","blasmeie","blasmeis","blasmeit","blasmer","blasmera","blasmeya","blasmez","blasmés"],
	"blecier" => ["blecier","blesce"],
	"blond" => ["blond","blonde","blondeite","blondete","blondette"],
	"boche" => ["boche","boche","bochete","boucete","bouche","bouchete","bouchette"],
	"boire" => ["boire","beuons","boire"],
	"bon" => ["bon","boen","boene","boens","boin","boine","bon","bone","bones","bonne","bonnes","bons","bouen"],
	"bonement" => ["bonement","bonement","bonnement"],
	"bos" => ["bos","boais","bois","boix","bos"],
	"boschage" => ["boschage","boscage","boscaige"],
	"branche" => ["branche","branchelle"],
	"bras" => ["bras","brais","bras","braz"],
	"brisier" => ["brisier","brisier","bruisiez"],
	"brun" => ["brun","brun","brune","bruneite","bruneites","brunet","brunete","brunetes","brunette","brunez","bruns"],
	"buisson" => ["buisson","buissonet"],
	"burelure" => ["burelure","beurelidon","burelaribu","burelidon"],
	"camusette" => ["camusette","camusette"],
	"caroler" => ["caroler","caroler"],
	"ceindre" => ["ceindre","chaindrai","saindrai"],
	"ceinture" => ["ceinture","ceinturete","sainturette","senturete"],
	"celer" => ["celer","celer","celerai","celleir","celler"],
	"cent" => ["cent","cent","cenz"],
	"chaloir" => ["chaloir","chault","chaut"],
	"chambre" => ["chambre","chambre","chanbre"],
	"chançon" => ["chançon","cançon","chan","chans","chanson","chansonettes","chançon","chançonete"],
	"changier" => ["changier","cangie","cangier","chaingier","change","changera","changerai","changier"],
	"chanter" => ["chanter","cant","canterai","cantés","chant","chantans","chantant","chante","chanteir","chanteis","chanteiz","chantent","chanter","chanterai","chanteray","chantez","chantot","chantés","chanz"],
	"chape" => ["chape","capelet","chaipelet","chape","chapeau","chapel","chapelet","chapiau","chapiaux","chappe","chappel"],
	"chascun" => ["chascun","cascun","cascuns","cescuns","chacun","chascun","chascune","chascuns","chaucuns","chauscun","chescuns","quancuns","quaucuns"],
	"chastel" => ["chastel","chasteau","chastel","chastelaine"],
	"chastier" => ["chastier","chaistit","chastie","chastit","chastoi"],
	"chetif" => ["chetif","caitiue","chaitif","chaitiue","cheitiue","chetif","chetis","chetiue"],
	"chevalier" => ["chevalier","cheualier"],
	"chois" => ["chois","chois","cois"],
	"choisir" => ["choisir","chesist","choisi","choisist","choisit","choisy","coisi","coisist","kieusist"],
	"chose" => ["chose","chose"],
	"cibalala" => ["cibalala","chabala","chibala","chibalala","chibele","chibera","chiberala","cibala","cibalala","ciua","ciuala","ciualala","ciualaladuriax","civa","civala","lachibele","lala"],
	"ciel" => ["ciel","ciel","cielz","ciex"],
	"clamer" => ["clamer","claim","claime","clamer"],
	"cler" => ["cler","cleir","cleire","cler","clere"],
	"coardie" => ["coardie","coardie","couardie"],
	"coart" => ["coart","coart","couars","couart","cowars"],
	"coie" => ["coie","coie"],
	"cointe" => ["cointe","coente","cointe","cointement","cointise"],
	"color" => ["color","color","coloree"],
	"comandement" => ["comandement","comandement","commendemant","conmandement"],
	"comander" => ["comander","comandeis","comans","comant","comanz","command","commande","commandons","commant","conmant","coumant","quemant","recoumandons"],
	"comencier" => ["comencier","comancement","comansier","comence","comencier","commencié","commencé","conmencha","conmencié","coumencier","enconmencié"],
	"compaigne" => ["compaigne","conpaianete","conpaignete","conpaingnete"],
	"compaignie" => ["compaignie","compaignie","compaingnie","compainz","conpaignie"],
	"compaignon" => ["compaignon","compaignon","compaingnons","compengnons"],
	"comporter" => ["comporter","comportas"],
	"conduire" => ["conduire","conduie","conduira","conduis","conduit"],
	"conforter" => ["conforter","confors","confort","conforteir","conforteis","conforter","confortez","confortés","conforz","consalz"],
	"congié" => ["congié","congiet","congié","coniei"],
	"conquerre" => ["conquerre","conquestee","conquester","conquis","conquix"],
	"corage" => ["corage","corage","corageus","coraige","courage","couraige"],
	"corre" => ["corre","corent","corrent","keurent","queurent"],
	"cors" => ["cors","cor","corps","cors"],
	"cortois" => ["cortois","cortois","cortoisie","courtoisie"],
	"cous" => ["cous","cous"],
	"covenir" => ["covenir","conuenist","conuent","conuient","convent","couegne","couent","couient","couuenir","couuenist","couuient"],
	"craindre" => ["craindre","crient"],
	"crever" => ["crever","crauent","creueir","creueront","creuerés","creuez"],
	"crier" => ["crier","cri","crie","crieir","criem","crier","crierons","crieront","cris"],
	"croire" => ["croire","creez","croi","croie","crois","croit","créés","recroie","recroit"],
	"cruel" => ["cruel","cruel","crueus","cruex"],
	"cruelment" => ["cruelment","crueilment"],
	"cuens" => ["cuens","cuens"],
	"cuer" => ["cuer","ceur","ceurs","coeur","cuer","cueret","cuers","cver","cvers","qer","queors","quer"],
	"cuidier" => ["cuidier","cuidai","cuiday","cuide","cuidoie","cuit","quidai","quide","quidie","quidiés","quidoie"],
	"daigner" => ["daigner","daigne","daigniez","daignoit","deigne","deigniés","deignoit","dengne","doigne","doigneis","doignest"],
	"damage" => ["damage","damache","damage","damaige","domage"],
	"dame" => ["dame","dama","dame","dames","damme","madame"],
	"damoisele" => ["damoisele","damoisele","damoiselle","demisele"],
	"dance" => ["dance","dance","dancele","danse","donnce"],
	"dancer" => ["dancer","dancer","dancerai","dancez","dancier","danciez","dancés","dansser","dançar"],
	"darion" => ["darion","darion"],
	"deable" => ["deable","deables","deaubles","diables","dyable","dyaubles"],
	"debonaire" => ["debonaire","deboinaire","deboinere","debonaire","debonere","debonnaire","debonnaires","debonoires","debounaire"],
	"debonairement" => ["debonairement","debonairement"],
	"debonaireté" => ["debonaireté","deboinereté","debonairetez","debonaireté","debonairetés","debone","debonereté","debonnaireté","debounereté"],
	"debrisier" => ["debrisier","debris","debrise","debrisent"],
	"decevoir" => ["decevoir","deceuans","deceuoir","decevoir","deceü","deceüe","decheuoir","deseuoir"],
	"deduire" => ["deduire","deduire","dedus","deduxans","desduire"],
	"deduit" => ["deduit","deduis","deduit","desduit"],
	"defendre" => ["defendre","deffendeis","deffendez","deffendrai","deffendre","deffendreis","deffendés","deffent","deffondés","desfendre","desfent"],
	"deine" => ["deine","deine"],
	"delarandurei" => ["delarandurei","delaradurelle","delarandurei"],
	"delaridon" => ["delaridon","delaridon"],
	"delit" => ["delit","delis","delit","delite","deliz"],
	"delivrer" => ["delivrer","deliura","delivra","delivrés"],
	"delle" => ["delle","delle","deme"],
	"delurele" => ["delurele","delurele","deluriau","deluriele","delurot","luroy"],
	"demain" => ["demain","demain"],
	"demander" => ["demander","demanc","demand","demande","demandee","demander","demandez","demanrait","demanrat","demant","demendez","demendz","qier"],
	"demener" => ["demener","demaine","demainne","demeinne","demener","demenne","demenra","demenrra","dement","demoinne"],
	"demorer" => ["demorer","demeure","demeurés","demoree","demorei","demoreit","demorer","demorez","demorrés","demoré","demorés","demour","demoure","demouree","demourer","demourez","demouré","demourés"],
	"departir" => ["departir","depairt","depars","depart","departie","departir","departirai","departirons","departiront"],
	"deporter" => ["deporter","deport","deporter"],
	"deservir" => ["deservir","desert","deserui","deseruie","deseruit","deservie","desserui","desseruie"],
	"desir" => ["desir","desir","desirant","desire","desiree","desireie","desireis","desirree","desirrés","dezir","dezirouze"],
	"desloial" => ["desloial","desleaus","desloiaus"],
	"destraindre" => ["destraindre","destaindre","destraigne","destraignent","destraigniez","destraindre","destraint","destrant","destrent"],
	"Deu" => ["Deu","deu","deus","deux","dex","dieu","dieus","dieux","diex","diu","dius","diux","dix","dié","djeus","djex","dues","duez","dé","endieu"],
	"deurelidele" => ["deurelidele","deurelidele","deurelidot"],
	"deus" => ["deus","deus","deux","dous","dui","ii","ij"],
	"devenir" => ["devenir","deuendra","deuendrai","deueneis","deuenez","deuenir","deuenrai","devient"],
	"deviner" => ["deviner","adeuiner","adevinez","deuiner"],
	"devoir" => ["devoir","deuez","deuoit","deuons","deuroit","deués","devons","devuons","deüst","doi","doibt","doie","doit","doiue","doueroie","douoir","doy"],
	"dire" => ["dire","di","dira","dirai","dirait","diraiz","diray","dire","direz","diroi","diroie","diroiz","dirra","diré","dirés","dis","diseteus","disoit","dist","dit","dite","dites","ditez","dittes","dixoit","diz"],
	"dis" => ["dis","dix","x"],
	"diva" => ["diva","diua","diuai"],
	"dodele" => ["dodele","do","dele","dodele","dodelle","dododo","dondele","dundele","dundeus"],
	"doi" => ["doi","doi","dois","doit","doy"],
	"dolent" => ["dolent","dolans","dolant","dolante","dolens","dolent","dolente","doulant"],
	"dolor" => ["dolor","delour","dol","doloir","dolor","dolors","dolour","dolours","dols","dolur","dolurs","doul","douleur","douleurs","doulor","doulors","doulour","doulours","dueil","duel","duels","duelz","duil","doloir"],
	"doloreusement" => ["doloreusement","dolorouzement"],
	"doloros" => ["doloros","delirous","dolereus","dolereux","dolerez","doleroz","doleureus","doulerous","douloureux"],
	"dondenne" => ["dondenne","dondenne"],
	"doner" => ["doner","doig","doing","doins","doinst","doint","don","donait","done","donee","donei","doneir","doneis","doneit","doneiz","doner","donez","donne","donnee","donnei","donneie","donneis","donner","donneray","donney","donnez","donné","donnés","donois","donrai","donray","donrray","donré","doné","donés","dorai","dorré","doune","dounee","douner","dounez","douné","dounés","dourrai"],
	"dorelot" => ["dorelot","deurenleu","deurenlev","doalot","doralot","doranlot","doreleu","dorellot","dorelo","doreloit","dorelot","dorenleu","dorenlo","dorenlot","dorenlou"],
	"doriaus" => ["doriaus","doreaus","dorele","dori","doriaus","doriaux","doriax","dorie","doudie","doura","doureaus","dourele","doureles","douri","douriaus","dourie","duduriaus","dural","durau","dureau","dureaus","dureaux","durei","durele","dureles","durelle","duri","duriau","duriaus","duriaux","duriax","durie","durien","duron","durot","duré","ladurele","laduriaus","ladurie","laladurete","ualidorele","ualidoré","valaliduré","vali","validoriax"],
	"dormir" => ["dormir","dorme","dorment","dormez","dormi","dormir","dormira","dormirai","dormiras","dormiray","dormirez","dormiroit","dormirés","dort","endormi","endormie"],
	"doucement" => ["doucement","docement","douceitement","doucement"],
	"douçor" => ["douçor","douchour","douchours","doulçor","dousour","douçor","douçour","douçours"],
	"dous" => ["dous","doce","doche","dolz","douc","douce","douces","doucete","doucette","douceurs","douche","douchette","doulce","doulces","douls","doulx","doulz","dous","doux","douz","dox","doz","tresdouce","tresdouz"],
	"douze" => ["douze","douze","xii"],
	"droit" => ["droit","drois","droit","droite","droiz"],
	"droiture" => ["droiture","droiture"],
	"druerie" => ["druerie","dru","drue","druerie","drues"],
	"duel" => ["duel","deuil","deul","deuls"],
	"dur" => ["dur","dures","durete","durette"],
	"durer" => ["durer","dure","dureir","dureis","durer","durerés","duret","dureya","durez","durra","duré","durés"],
	"embler" => ["embler","amblee","amblei","amblé","emblé","enbleit","enblé"],
	"emporter" => ["emporter","j'emporte","l'emport","l'enport"],
	"endurer" => ["endurer","andurer","endure","endureir","endurer","endurez","enduroi","enduron","enduré","endurés","i'enduir","i'endur","j'endur","l'endure"],
	"enemi" => ["enemi","anemi","anemis","anemmi"],
	"enporter" => ["enporter","enporta"],
	"enseignier" => ["enseignier","enseigner","m'ensaigne","m'ensaingne","m'ensegne","m'enseigne","m'enseigniez","m'enseigniés"],
	"entendre" => ["entendre","antendre","entendez","endendray","entendre","endentroit","entendroy","entendés","j'entendray","m'entendroie"],
	"entier" => ["entier","entier","entiere","entire"],
	"entierement" => ["entierement","entieremant"],
	"entremetre" => ["entremetre","m'entremete"],
	"entrer" => ["entrer","antrai","entree","entrer","entrez","entré","entrés"],
	"entroblier" => ["entroblier","entroblier","entroublier","entrobliee","entroubliee","m'antroblie","qu'entrobliee"],
	"envier" => ["envier","anvie","d'envie","enviz"],
	"envieus" => ["envieus","anious","anvïous","enuieus","enuious"],
	"envoisier" => ["envoisier","anuoixie","anvoisie","anvoixie","enuoisie","enuoisiés","enuoixiés","envoisie","m'anuoise","m'enuoise","m'enuoiserai","m'envoise","ranuoisie","ranvoisie","renuoise","renuoiserai","renuoisie","reuoisier","renuoisies","renuoisiez","renuoisié","renuoisiés","renvoisera","renvoisie","renvoisier","renvoisiez","renvoisiés","renvoysiez"],
	"envoier" => ["envoier","anuoie","enuoi","envois","m'enuoit","m'envoie","renuoit","renvoit"],
	"esbaudir" => ["esbaudir","esbaudir","esbaudis"],
	"escolter" => ["escolter","escote","escoute"],
	"escondire" => ["escondire","escondis","l'escondire"],
	"escrire" => ["escrire","escript","escripte","escris","escrit"],
	"esjoïr" => ["esjoïr","esioïr","esioïs","resioïr","resjoïr"],
	"esloignier" => ["esloignier","eslognie","esloignie","esloigniet","esloigniez","eslongie"],
	"espaourer" => ["espaourer","espaouree"],
	"esperance" => ["esperance","esperance","m'esperance"],
	"esperer" => ["esperer","esperant","espereir","esperer"],
	"espoenter" => ["espoenter","enpoentee","espauentee","espoantee","espoentee"],
	"espoir" => ["espoir","espoair","espoi","espoir"],
	"espringuier" => ["espringuier","espringas","espringuaz","espringuez","espringuiez","espringués","l'espringuier"],
	"espris" => ["espris","espris"],
	"estraine" => ["estraine","estrainne","estrene","estrine"],
	"estovoir" => ["estovoir","l'estuet","m'estuet"],
	"estrange" => ["estrange","estraigne","estrainge","estrange","estrengne"],
	"esveiller" => ["esveiller","esueilliez","eueilliez","l'esueillerai","l'esuellerai","l'esvellerai","m'esuaille","m'esueille","resueille","resueillent","resuelle"],
	"eure" => ["eure","eure","eures","heure","heures","houre"],
	"eureusement" => ["eureusement","eüreusement"],
	"eya" => ["eya","ea","eai","eein","eeus","ei","eo","eois","eou","ey","eya","eyal","eyaut","eyent","eyeus","eyois","eyoit","eyous","eyr","eyt","eyu","eyuer"],
	"faillir" => ["faillir","fail","faille","failli","faillie","faillir","faillis","faillit","fali","fallier","fallir","faut"],
	"faindre" => ["faindre","faindrai","faindre","faing","faingi","fau"],
	"faitis" => ["faitis","faitissete","faitissette"],
	"faloir" => ["faloir","faudra","faudrai","faudroit","faudront","fauldra","faura","fauriez","fauront","faurra"],
	"falser" => ["falser","faceir","fauce","fauceir","faucer","faul","faulce","faus","fausai","fause","fausee","fauser","faussai","fausse","fausser","faussera","fausserai","faussé","faussés"],
	"faussement" => ["faussement","faucement"],
	"felon" => ["felon","fellons","felon","felons"],
	"feme" => ["feme","fame","feme","femme"],
	"fi" => ["fi","fi","fj"],
	"fille" => ["fille","fille"],
	"fin" => ["fin","fin"],
	"fin" => ["fin","fin","fine","fines","fins","finz","fjnes"],
	"flajol" => ["flajol","flagieu","flagol","flagoler","flaioler","flaiot"],
	"flor" => ["flor","fleurs","flor","flors","flos","flour","flours","flourz","flur"],
	"florir" => ["florir","flori","florie","flourie","flourir"],
	"foi" => ["foi","foi","foy"],
	"foil" => ["foil","foilli","fueille","fueilli"],
	"fol" => ["fol","fol","fole","folle","fols","folz","foul","foulz","fous","foux","fox"],
	"folement" => ["folement","folement"],
	"folie" => ["folie","folage","folaige","folie","foliete","follour","folor","folur"],
	"foloier" => ["foloier","filiier","foliier","foliser","folloié","foloi","foloie","foloier","foloié"],
	"gai" => ["gai","gai","gaie","gais","gay"],
	"garçon" => ["garçon","garchon","garçon"],
	"garder" => ["garder","gairdeir","gairderai","garde","gardeis","gardeiz","garder","garderai","garderoit","gardez","gardés","guardee","guardez"],
	"garir" => ["garir","garie","garir","garira","garirai","garirat","garis","garist","garit","garrai","garray","garrirai","guarie","guarira","guariroie","guerira","guerirai","guerirait","guerireiz","guerist","gueriz","guerra","guerrai"],
	"garison" => ["garison","garison","gherredon","gueredon","gueridon","guerison","guerredon"],
	"gaudine" => ["gaudine","gaudine"],
	"gens" => ["gens","gens","genz","iant","ianz"],
	"gent" => ["gent","gens","gent","gente","gentee","gentils","gentis","genz","iente"],
	"gnif" => ["gnif","gnaf","gnauf","gnief","gnif","gnof","gnouf"],
	"grace" => ["grace","grace","gracieuse","gracieusette","graciouse"],
	"grant" => ["grant","grand","grans","grant","granz"],
	"gré" => ["gré","gree","grei","greif","greis","greit","grez","gré"],
	"grevance" => ["grevance","greuance","greuence"],
	"grever" => ["grever","greuee","greueir","greueit","greuer","greuet","greué","grevet","grevé","grieue","griué"],
	"grief" => ["grief","grief","griez","griés"],
	"guerpir" => ["guerpir","guerpi","guerpie","guerpisiez"],
	"guiler" => ["guiler","ghille","guile","guiler","guiller","guilleurs","guillier"],
	"haer" => ["haer","haez","haieiz","haiez","hais","hait","haï","haïr","haïs","haÿr","hee","hei","heit","het"],
	"hahai" => ["hahai","ahai","hahai","hahye","haihai"],
	"haro" => ["haro","hairo","hareu","hareus","haro","harou","herou"],
	"haut" => ["haut","hault","haut","haute"],
	"hautement" => ["hautement","hautement"],
	"hé" => ["hé","aé","e","é","hai","hé"],
	"helas" => ["helas","elais","elas","helas","halas"],
	"hom" => ["hom","hom","home","homme","hons"],
	"honir" => ["honir","honi","honie","honir","honis","honit","honiz","honni","honnie","honnis","honnist","honniz","honny","houni","hounis","hounist","oniz"],
	"honte" => ["honte","hontage","honte"],
	"hu" => ["hu","hu"],
	"huer" => ["huer","huer"],
	"hui" => ["hui","hui","huy"],
	"hureliva" => ["hureliva","hureliua","hureliuai","huva","heuva","heuvien"],
	"jamais" => ["jamais","iamais","iamaix","iamez","iamés","jamais","jamaix","jamés"],
	"jalous" => ["jalous","gielos","ialos","ialous","ialouz","jalous","jaloux"],
	"jalousie" => ["jalousie","ialousie","jalousie","jaloussie"],
	"Jesus Christ" => ["Jesus Christ","crist","criz","iesus","ihesu","ihesucris","jhesu","jhesucris","jhesucrist","jhesucriz"],
	"jeu" => ["jeu","gieu","gieus","ieu","ieux","jeux"],
	"joene" => ["joene","iennes","iennete","ieune","ioeme","ioene","ioenete","ioenne","ioine","ione","iones","ionete","ionette","iouene","iouenete","jeunete","joenne","jone"],
	"joer" => ["joer","ioeir","ioer","ioier","iouer","iue","iueir","iuer","iut","jeut","joer","joiant","jouer","jut","juweiz"],
	"joie" => ["joie","goie","ioe","ioiant","ioianz","ioie","ioieuse","ioir","iois","ioye","joie","joiee","joye"],
	"joint" => ["joint","iointes","jointe","jointes"],
	"joïr" => ["joïr","ioïr","reioïr"],
	"jolieté" => ["jolieté","iolietei","iolieté","ioliuetez","ioliueté","ioliuetés","ioliveté","joliuetés","joliuetez"],
	"jolietement" => ["jolietement","ioletement","ioliement","iolietement","ioliettement","ioliuement","ioliuetement","jolemant","joliement","jolietemant","jolietement","joliettement","joliuement"],
	"jolif" => ["jolif","iolete","ioli","iolie","ioliete","iolietes","ioliette","ioliettes","iolif","iolis","iolit","ioliue","ioliuet","ioliuete","ioliuetes","iolive","jolivet","ioliz","joli","jolie","joliete","joliette","joliettes","jolif","jolis","jolit","joliue","joliuetes","joliuettes","jolive"],
	"jor" => ["jor","ior","iors","iorz","iour","iours","iourz","jor","jors","jorz","jour","jours"],
	"jurer" => ["jurer","iureit","iuré"],
	"lairele" => ["lairele","laierele","lairele"],
	"laissier" => ["laissier","laira","lairai","lairait","lairay","laire","lairez","lairiai","lairoie","lairons","lairés","lais","laise","laissai","laisse","laissent","laissiez","laissié","laissiés","laist","lait","laixe","laixet","lara","larai","lareis","last","leira","leirai","leisse","leissier","leit","lerai","leray","lerez","leroie","leré","lerés","lessai","lesse","lessent","lessiez","lessié","lest","let"],
	"langor" => ["langor","langor","langour","languir","languirai","languissant","languissiés","languit","languor"],
	"languir" => ["languir","laguir"],
	"lareu" => ["lareu","lareu"],
	"legier" => ["legier","legier"],
	"legierement" => ["legierement","legierement"],
	"lever" => ["lever","leuee"],
	"libodaine" => ["libodaine","libodainne","libodine"],
	"lié" => ["lié","liez","lié","liét"],
	"liement" => ["liement","liement","liéement","lyement"],
	"lieu" => ["lieu","leu","lieu","liu"],
	"loer" => ["loer","lo","loeie","loeir","loer","loi","los","lot","lout","lox","loz"],
	"loing" => ["loing","loig","loing","loins","loinz","léenz"],
	"lointain" => ["lointain","loigtaigne","loigtaine","lointainne","lontaigne","lontain","lontaing","lontaingne","lontainne"],
	"lonc" => ["lonc","lonc","longue","lons","longe"],
	"longement" => ["longement","longement","longhement","longuement","longuent"],
	"loial" => ["loial","laial","leal","leaul","leaus","leaux","leial","loal","loial","loials","loialz","loias","loiau","loiaul","loiaus","loiax","loyal","loyalz"],
	"loialté" => ["loialté","leaultei","leauté","loialteis","loialteit","loiaulteit","loiautez","loiauté","loiautés"],
	"loiaument" => ["loiaument","laiaument","lealment","leaulment","leaumant","leaument","leialment","leiamant","leiaument","liaument","loamant","loialment","loiaulment","loiaumant","loiaument","loiaumet","loyaulmt","loyaument"],
	"main" => ["main","main","mains","mein","meins"],
	"maintenir" => ["maintenir","maintaigne","maintanrai","maintendrai","maintenir","mainterai","mainterrai","maintienent","maintiennent","maintient","mentainrai"],
	"maintien" => ["maintien","mentiens"],
	"mal" => ["mal","mal","male","mals","malt","malx","malz","mau","maul","mauls","maulx","maulz","maus","maux","mauz","max"],
	"malade" => ["malade","malades","maladie","malaides"],
	"malage" => ["malage","malage","malaige"],
	"malement" => ["malement","malement"],
	"maleur" => ["maleur","mescheance","mescheans","mescheanz","meschief","mescreance"],
	"maleuros" => ["maleuros","maleuroz"],
	"malvais" => ["malvais","maluais","mauais","mauaistié","mauuais","mauuestié","mauuez","mauués","mauvais","mauvés","maués"],
	"mamele" => ["mamele","mamele","mameletes","mamelettes"],
	"mander" => ["mander","mandez","mandé","mandés","mant"],
	"mangier" => ["mangier","mengerons","mengier"],
	"mantel" => ["mantel","mentel"],
	"mari" => ["mari","mari","maris","marit","mariz","mary"],
	"mariage" => ["mariage","mariage","mariaige","mariai"],
	"marier" => ["marier","maria","marie","mariee","marieie","marieir","marier","mariera","marierai","marieray","mariez","marié","mariés"],
	"Marie" => ["Marie","marie"],
	"matin" => ["matin","main","matinee"],
	"mener" => ["mener","maignent","maine","mainent","mainne","mainreiz","maint","meine","meinne","menant","meneis","mener","menez","menons","menrai","menrons","moine","moinne","moinreiz","moinrons","moinrés"],
	"mentir" => ["mentir","mant","mantir","mens","ment","menti","mentir","mentit"],
	"merci" => ["merci","merce","merchi","merchis","merchit","merchy","merci","mercis","mercit","merciz","mercy","mersis","mersit","mierchi","mierci"],
	"mere" => ["mere","meire","mere"],
	"meschoisir" => ["meschoisir","meschoisy","meschosi","mescoisi"],
	"mesdisant" => ["mesdisant","medisans","medissans","medixans","medixant","mesdisans","mesdisant","mesdisanz","mesdissans","mesdixans","mesdis"],
	"mesfait" => ["mesfait","meffaire","meffait","meffet","mesfait"],
	"mesnage" => ["mesnage","mainage","mesnage","mesnaige"],
	"mesprendre" => ["mesprendre","mespris"],
	"message" => ["message","message","messages","messaige"],
	"mestier" => ["mestier","mestier"],
	"metre" => ["metre","mectre","meit","met","mete","meteis","metez","metre","mettre","metés","meïst","mis","mise","mist"],
	"mignot" => ["mignot","mignos","mignot","mignote","mignoz","mingnot"],
	"mignotement" => ["mignotement","mignotemant","mignotement","minoigrement","minoigtement"],
	"mignotise" => ["mignotise","mignostie","mignotise","mignotixe","mingnotise"],
	"mil" => ["mil","mil","mile"],
	"moine" => ["moine","moignes","moine"],
	"mont" => ["mont","monde","mons","mont","monz","munt"],
	"morir" => ["morir","morai","morait","morir","morra","morrai","morrez","mors","mort","moru","morut","morz","moura","mourir","mourrai","mourroi","muer","muert","muir","mur","muyr"],
	"mot" => ["mot","mot"],
	"movoir" => ["movoir","mouoir","mouuoir","movoir","muet"],
	"musardie" => ["musardie","musardie"],
	"musart" => ["musart","musairs","musant","musar","musars","musart","muzairs","muzant","muze"],
	"navrer" => ["navrer","nauree","naurei","naureis","naureit","naurez","nauré","naurés","navré","noble","noblesce","noblette"],
	"noce" => ["noce","noces"],
	"nom" => ["nom","nom","nons"],
	"nomer" => ["nomer","nomeir","nomer","nommer","noumee"],
	"nonne" => ["nonne","nonette","nonne","nonnete","nonnette","nounain"],
	"norrir" => ["norrir","norie","norrie","nouri","nourreture","nourri"],
	"noter" => ["noter","note","notes","notois"],
	"novel" => ["novel","nouel","nouele","noueles","nouelet","noueletes","nouelle","nouelles","nouiaus","nouuel","nouuele","nouueletes","nouuelletes","nouuellettes","nouuiau","nouuiel","nouuieles","nouvel","nouveles","nouvellettes"],
	"noveletement" => ["noveletement","nouellement","nouueletement"],
	"nuire" => ["nuire","nuira","nuisoit","nuist","nuit"],
	"nuit" => ["nuit","nuit","nuyt"],
	"obeir" => ["obeir","obeir","obeïr"],
	"oblier" => ["oblier","c'oblier","m'oblieis","m'oblieiz","m'obliez","m'obliés","m'oublie","m'oubliez","m'oubliés","m'ublit","n'obli","n'oblieiz","n'oblierai","n'oubli","n'oublierai","obli","oblie","obliee","oblier","oblierai","oubli","oublie","oubliee","oublieit","oublier","oublierai","oubliez","oubliier","oubliés"],
	"ocire" => ["ocire","l'ocirroie","l'ocist","m'occhie","m'occhirra","m'occirra","m'occist","m'occit","m'ochi","m'ochie","m'ochient","m'ochira","m'ochirra","m'ochirrés","m'ochist","m'ochiés","m'ocidrait","m'ocie","m'ocieis","m'ocieiz","m'ocient","m'ociez","m'ocira","m'ocirait","m'ocireis","m'ocireiz","m'ocirez","m'ociront","m'ocirra","m'ocirreis","m'ocirrez","m'ocirroiz","m'ocirrés","m'ocirés","m'ocist","m'ocit","m'ociés","m'orciroiz","m'orcirrez","m'oscist","m'osidrait","m'osie","m'osient","m'osist","n'ocieis","n'ociez","n'ocirrez","n'ociés","oci","ociroie","ocis","ocit","ocys"],
	"ochoison" => ["ochoison","d'achoison","l'ochoison","l'ocoison","ochoison","oquison"],
	"odeli" => ["odeli","deli","delio","odeli"],
	"oeil" => ["oeil","eill","elz","eul","eulz","eus","euz","huil","ieulz","ieus","ieuz","iex","l'eul","l'ueil","l'uel","oeil","oeill","oel","oeul","oil","ouel","ueil","yeulx","yeux","yex"],
	"oeuvrer" => ["oeuvrer","oureir","l'ueure"],
	"oïr" => ["oïr","i'oi","i'oie","j'oi","j'oï","l'orrez","l'orrés","oez","oiiés","oiés","orrez","oï","oïr"],
	"oisel" => ["oisel","l'oiselet","oiseillon","oiseillons","oisellons","oiselons","oisillon","oisillons","oyseillons","oysillons"],
	"oix" => ["oix","oix"],
	"onor" => ["onor","c'onors","c'onours","d'onneur","d'onor","d'onour","deshonur","hennor","hennorez","hennour","henoree","henours","honneur","honnour","honor","honors","honour","honur","hounour","hounours","k'onours","l'onor","qu'oneurs","s'eneur","s'oneur","s'onor"],
	"onorer" => ["onorer","honnourés","honoreis","honorez","honorés"],
	"orguil" => ["orguil","orgoel","orgoil","orgueil","orgueilg","orgueill","orguel","orguilleusette"],
	"oser" => ["oser","i'osasse","i'osoie","i'oussexe","l'os","l'ose","l'osoie","l'ozoie","n'olz","n'os","n'ose","n'oz","os","s'osaixe","s'ose"],
	"oster" => ["oster","osteir","osteis","oster","ostez","ostés"],
	"otroier" => ["otroier","m'ostroi","m'otriiés","m'otroi","m'otroie","otrai","otrie","otroi","otroie","otroit","ottrie","s'otroie"],
	"ovrir" => ["ovrir","ourez"],
	"paor" => ["paor","paor","paour","paours","poour","pouur"],
	"paradis" => ["paradis","paradis","pareïs"],
	"parçonerie" => ["parçonerie","parchonerie","parchonnerie","parsonerie","parçonerie","parçonnerie","perçonnerie"],
	"parçonier" => ["parçonier","parçoniers"],
	"pardoner" => ["pardoner","pardonez","pardonnee","pardonnez","pardonnés","pardonés","pardounee"],
	"parler" => ["parler","pairleir","parelle","parleir","parleis","parlement","parler","parlez","parliere","parole"],
	"partir" => ["partir","pairt","part","parti","partir","partira","partirai","partiroi","partiré","partis","partés","pertirai","pertirait"],
	"parvenir" => ["parvenir","paruient"],
	"passer" => ["passer","paisse","pascent","passe","passent","passer","passerai","pessent"],
	"pastorele" => ["pastorele","pastorele","pastorelle","pastourele"],
	"pasture" => ["pasture","pasture","pasturrons"],
	"païs" => ["païs","païs","païx","paÿs"],
	"peine" => ["peine","paine","paines","painne","peine","peinne","pene","poene","poine","poinne"],
	"pendre" => ["pendre","pendre","penduz"],
	"penser" => ["penser","pance","pancee","panceir","panceirs","pancer","pans","panse","pansee","panser","pansez","pansé","pencee","penpense","pens","pensant","pense","pensee","penseir","pensent","penser","pensers","pensez","penssai","penssant","pensse","pensser","penssers","penssé","pensé","pensés","repenser"],
	"perdre" => ["perdre","esperdus","perc","perch","perdrai","perdu","perdue","perdues","perdus","perdut","perdés","pert","pierdues"],
	"pervenche" => ["pervenche","peruenche","venke","venque"],
	"petit" => ["petit","petit","petitet"],
	"pie" => ["pie","pie","piot"],
	"piteus" => ["piteus","piteus","piteuse","pitous"],
	"pitié" => ["pitié","pieteit","pitei","piteit","pitiet","pitié","pitiés","pité","pités"],
	"plaindre" => ["plaindre","plaig","plaign","plain","plaindre","plaing","plaint"],
	"plaire" => ["plaire","plai","plaira","plairait","plaist","plait","pleist","plera","plere","plest","pleüs","pleüst"],
	"plaisant" => ["plaisant","paisans","plaisans","plaisant","plaisanz","plaixans","plaixant","pleisant","plesant","plesanz"],
	"plaisamment" => ["plaisamment","plaisamment"],
	"plaisir" => ["plaisir","plaisir","plaixir","pleisir","plesir"],
	"plein" => ["plein","plaine","plainne","plains","plein","pleine"],
	"plorer" => ["plorer","enplorra","pleure","pleurer","plorant","plore","plorer","ploure","plourer"],
	"poindre" => ["poindre","poignent","poingnent","poins","point","poize"],
	"poissant" => ["poissant","poisance","poissans"],
	"pooir" => ["pooir","neporoie","peult","peus","peut","poent","poet","poez","poi","pois","poist","poit","pooir","poons","pora","porai","poray","poroie","porra","porrai","porret","porrey","porroie","porroit","porés","pot","pouez","pourez","pourrai","pourrey","pourroie","pu","puet","puez","puise","puisse","puissent","puist","puix","puixe","puiz","pux","puxe","pués","reporoie","reporroie"],
	"porter" => ["porter","port","porta","portas","porte","porteir","porter","pourtei"],
	"povre" => ["povre","poure","poures"],
	"pré" => ["pré","pré","prés"],
	"premier" => ["premier","premier","premieres","premiers","prumieres"],
	"prendre" => ["prendre","enprandre","praigne","praingne","prandre","prandroie","prant","pregne","preigne","preignent","prend","prendeis","prenderai","prendra","prendrai","prendre","prendroie","prendés","prenez","prennés","prent","prenés","prest","prins","print","pris","prise"],
	"present" => ["present","presant","present"],
	"preu" => ["preu","preu","preux","preuz","prous","proz"],
	"prier" => ["prier","pri","prie","prier","priez","priiés","priés","proi","proiant","proie","proiiés","proiés"],
	"pris" => ["pris","prix","priz"],
	"prisier" => ["prisier","prisier"],
	"prison" => ["prison","l'enprisonnee","prison","prisonniers","prixon","prizon"],
	"prochain" => ["prochain","procaine","prochain","prochaine","prochainemant","prochainne"],
	"prometre" => ["prometre","promectre","promettre"],
	"prover" => ["prover","proeue","prouerai","prueue"],
	"pucele" => ["pucele","pu","puce","puceille","pucele","pucelete","pucelle","puchele","puchielle"],
	"quatre" => ["quatre","quatre"],
	"quedonda" => ["quedonda","quedonda","quedondi"],
	"quere" => ["quere","acquise","kier","qer","quer","querai","querez","querrai","quier","quiert","quir","quis","quise"],
	"quinze" => ["quinze","xv"],
	"rage" => ["rage","rage","raige"],
	"raison" => ["raison","raison","raisons","raixon","reison","reson","resons"],
	"ramee" => ["ramee","raim","raimme","rain","ramee","ramé"],
	"ramener" => ["ramener","ramaint","ramenee","ramenez"],
	"recovrer" => ["recovrer","recoureir","recourer","recouré","recouuree","recouurer","recouuré"],
	"regarder" => ["regarder","d'eswarder","esgair","esgairt","esgar","esgarde","esgardeis","esgarder","esgardés","esgart","regardai","regardant","regarde","regardez","regardés","resgardez","resgars","resgart","resgarz","rewars"],
	"regart" => ["regart","regairt","regard","regars","regart","regarz","regaz","rigars"],
	"resconforter" => ["resconforter","desconforte","desconfortee","reconforte","reconforteir","reconforter","resconforteis"],
	"remanoir" => ["remanoir","remaingne","remaint","remait","remandra","remanoir","remenans"],
	"remembrer" => ["remembrer","menbre","remembrance"],
	"remirer" => ["remirer","remir"],
	"rendre" => ["rendre","rans","rant","ren","renc","rende","rendent","rendez","rendre","rendroit","rendré","rendt","rens","rent"],
	"renoveler" => ["renoveler","renouele","renouuele"],
	"renvoisiement" => ["renvoisiement","renuoisiement","renvoisiement"],
	"repentir" => ["repentir","repant","repantez","repantir","repen","repent","repente","repenterai","repentez","repentir","repentira","repentirai","repentirait","repentiray","repentons","repentés"],
	"reporter" => ["reporter","reportez","reportés"],
	"reposer" => ["reposer","repos","reposeir","reposer","reposon"],
	"requere" => ["requere","reqerrai","reqier","requier","requise"],
	"revenir" => ["revenir","reuenderont","reuenez","reuenue","reuenuz","reuenés","reuienne","reuient"],
	"reverdie" => ["reverdie","renuerdie","reuerdie"],
	"reveoir" => ["reveoir","reuairai","reueoir","reuerrai","reuerré","reuoer","reuoie","reuoir","reuëoir","reverrai","reverré","revoie","revoye"],
	"rire" => ["rire","ri","rians","riant","rirai","rire","ris","rist","rit","riz"],
	"rose" => ["rose","rose","rosier"],
	"rossignol" => ["rossignol","roissignolet","rosignol","rossignol","rossignolet","rossingnol","rousignol","rousignollet","roxingnol","roxingnols"],
	"sade" => ["sade","sade","sades","sadete"],
	"saderalidon" => ["saderalidon","laridon","sadela","sadelaridon","sadelarire","sadeliua","sadera","saderala","saderaladon","saderali","saderalidoré","saiderora","lidoré","liduré","liredurei"],
	"saige" => ["saige","sage","sages","saige","saiges","saigette"],
	"saint" => ["saint","sains","saint","sainte","sainz","seinz"],
	"saisir" => ["saisir","saisi","saixi","saixit","saizi"],
	"saison" => ["saison","saison","seson"],
	"saluer" => ["saluer","saluee","salueir","salueis","saluez","salus","salut","salués"],
	"savoir" => ["savoir","sache","sachiez","sachiés","safret","sai","saiche","saichiez","sarai","sarez","sariés","saroie","saroit","saront","sarés","saueis","saueront","sauez","sauiés","sauoir","sauoit","saurai","saurait","saurez","sauriez","sauroie","sauroit","sauront","saurés","saués","saverai","savoit","savront","say","sçai","sçauoir","sçauront","sçaués","sçavez","sçavoir","sçay","scet","seit","set"],
	"savoreus" => ["savoreus","saouree","saoureux","sauerosete","sauerouse","sauerousete","sauerouze","sauerouzette","saueroz","sauerus","saueureus","sauoreus","sauoreuse","sauoreusete","sauorosete","sauouree","sauoureus","sauoureuse","sauoureusete","sauoureusette","sauoureux","sauouros","sauourosete","sauourous","sauourousete","sauuereux","saverouze","savoreus","savoreusete","savoros"],
	"secors" => ["secors","secorrés","secors","secorés","secourez","secourre","secours","secourés","soucourés"],
	"seignor" => ["seignor","seignor","seignorie","seignourie","seignur","signorie","signourie","singnourie"],
	"sejor" => ["sejor","seior","seiour","sejour"],
	"sembler" => ["sembler","samblance","samblant","samble","sanbleroit","sanlant","semblance","semblant"],
	"sentir" => ["sentir","sant","santez","santi","santit","sen","senc","sench","sens","sent","senteiz","sentent","sentez","senti","sentir","senté","sentés","senz"],
	"servir" => ["servir","serf","sert","serui","seruice","seruie","seruies","seruir","seruira","seruirai","seruiroi","seruisce","seruise","seruixe","servi","services","servir","servirai","sierui","sieruir"],
	"simple" => ["simple","simple","simplete","simplette","sinple"],
	"sire" => ["sire","sir","sire","sires","sjre"],
	"sofrir" => ["sofrir","seuffre","soffrir","sofrir","sosfrir","souffrir","soufrir","soufrés","sousfrir","sueffre"],
	"sol" => ["sol","seule","seulete","seulette","seullete","seullette","soul","soule","soulette"],
	"solas" => ["solas","solais","solas","solaus","solaz","soulas","soulaus","soulaz"],
	"soloir" => ["soloir","soloie","souloie","sueil","suel","suieil","suil"],
	"songe" => ["songe","songe","songier","songoie"],
	"sorprendre" => ["sorprendre","seurpris","seurpriz","sopris","sorprendre","sorpris","sospris","soupris","sourpris","souspris"],
	"sospir" => ["sospir","sopir","sospir","sospirs","soupir"],
	"sospirer" => ["sospirer","sopireir","sospirer","soupirant","soupirer","souspirant","souspirer"],
	"sostenir" => ["sostenir","sostient","soutenez","soutient"],
	"sosvenir" => ["sosvenir","resosuient","resouient","resouuient","sosuiegne","souaigne","soueigne","souiegne","souiengne","souigne","souueigne","souuiegne","souuiengne","souuienne","souuient","souuigne","souvigne"],
	"sot" => ["sot","sot","sotte"],
	"tart" => ["tart","tart"],
	"tendre" => ["tendre","tench","tendez","tendrai","tendre","tendront","tendu","tenrai","tenroit"],
	"tenir" => ["tenir","taig","teent","teignent","teneis","tenent","tenez","tengne","tenir","tenist","tenoie","tenoye","tenés","tieg","tiegne","tiegnent","tien","tienent","tieng","tiengne","tiennent","tiens","tient","tinent","ting","tint"],
	"tens" => ["tens","tens","tans","tanz","temps"],
	"terre" => ["terre","terre"],
	"tesmoignier" => ["tesmoignier","tesmoignent"],
	"tochier" => ["tochier","atouche","n'atouche","n'atoucherez","n'atoucheroiz","n'atoucherés","n'atouchiez","n'atouchiés","touche","toucher","touchier"],
	"toler" => ["toler","tolez","tolt","tolu"],
	"torcher" => ["torcher","torcher"],
	"torment" => ["torment","tormant","torment","tormente","tourment"],
	"torner" => ["torner","tornanz"],
	"tornoiement" => ["tornoiement","tournoiement"],
	"traili" => ["traili","traili","traire","trairi","trairire","trarire"],
	"traïr" => ["traïr","trahi","trahie","trahir","trahirai","trahis","trahison","trahy","traï","traïr","traïs","traïson","traïssent","traïsun","traït","traïxon","traïz","traÿ","traÿson"],
	"traire" => ["traire","traez","trahet","trahez","trai","traie","traiez","traire","trairés","trais","trait","traités","traiés","tray","treez","treiez","tret","treés","tré"],
	"travaillier" => ["travaillier","trahoulier","trauaille","trauailliez","trauailliés","trauaillé","traual","trauaus","traueilliez","trauelliés","trauilliez","trauilliés","trauoiller","traveilliez"],
	"trebuchier" => ["trebuchier","trebuchié","trebucier"],
	"trente" => ["trente","trente"],
	"triboudaine" => ["triboudaine","triboudaine","triboudainne","triboudel"],
	"trichier" => ["trichier","trice","triche","tricherie"],
	"tridon" => ["tridon","tridenne","tridon"],
	"triquedondaine" => ["triquedondaine","trikedondaine","trikedondainne","trikedondene","trikedondenne","triquedondele"],
	"triste" => ["triste","triste","tristor"],
	"trois" => ["trois","iii","trois","troys"],
	"trover" => ["trover","retrouuee","treuue","troeue","trouai","trouaist","trouee","trouees","trouei","troueie","troueir","troueit","trouer","trouerai","trouerez","trouerés","trouez","trouuai","trouuee","trouuees","trouuer","trouuerai","trouué","trouvai","trouvee","trouver","trouvé","troué","trovei","trover","trové","truis","truix","trux"],
	"truffer" => ["truffer","truffe","truffes"],
	"tuer" => ["tuer","tue","tuez"],
	"turelure" => ["turelure","teirelire","teireliredon","teureleure","tuereleure","turelure","turelicta","turelutea","turulurita","turuluruta","tura","turait","ture"],
	"uis" => ["uis","l'uis","l'uix","l'uys"],
	"umblement" => ["umblement","humblement"],
	"usage" => ["usage","usage","vsage","vsaige"],
	"user" => ["user","s'uze","useir","vseir"],
	"vadeure" => ["vadeure","ua","uadeurelidot","uadi","uadoie","uadou","uadreu","uadu","uaudeure","va","vadalaridon","vadelarirondé","vaderalidou","vadeure","vadeurelidele","vadeurelidot","vadou","vadourenne","vadu","vauadreu","vaudeure"],
	"vaillant" => ["vaillant","uaillans","uaillant","vaillans","vailliant"],
	"vaincre" => ["vaincre","ueincu","vaint","veincu"],
	"vair" => ["vair","uair","uairs","ueir","ueirs","vair","vairs"],
	"valara" => ["valara","ualala","val","vala","valala","valara","valarara","valereu","vallereu","valleureu"],
	"valet" => ["valet","uallet","uarlet","uaslet","vallet"],
	"valee" => ["valee","ualee","valee","vallee"],
	"valoir" => ["valoir","uaillet","ualeis","ualoir","ualour","uaudra","uaudrai","uaut","valez","valoir","valour","valés","vaudrai","vaudroie","vauldra","vaulrai","vaurai","vaurés","vaut"],
	"valuraine" => ["valuraine","ualuraine","ualuru","valuraine","valuru"],
	"vanter" => ["vanter","uante","uantent","uanter","uentent","vante","vantent"],
	"vassal" => ["vassal","vassal"],
	"veillier" => ["veillier","ueillier","ueilliés","uellier","uieillier","veillier"],
	"vendre" => ["vendre","uant","uent","vent"],
	"venir" => ["venir","uaigne","uanra","uanrait","uendra","uendrai","uendront","ueneis","uenez","uenir","uenra","uenrai","uenus","uenuz","uenés","uiegne","uien","uient","uint","vaingne","vandra","vendra","vendrez","venez","venir","venra","venrai","venrez","venuz","viegme","viegne","viegnent","vien","viengne","viengnent","viennent","vient","vignent","vins","vint","vinz"],
	"veoir" => ["veoir","uairai","uaïr","ueoir","uerrai","uerrez","uerroie","uerré","uerrés","ueré","ueu","ueïr","ui","uoer","uoi","uoie","uoir","uois","uoit","uoy","ve","veez","veoir","verrai","verras","verray","verrez","verroie","verroye","verrés","vesrai","vez","veïr","veüe","vi","vit","voi","voie","voir","voit","voix","vouoir","voy","vé","vés"],
	"verité" => ["verité","ueriteit","uerité","verité"],
	"vermeillete" => ["vermeillete","uermeillete","uermillete","uermoillette","vermeillete","vermoillete"],
	"vert" => ["vert","uert","vers","vert"],
	"viaire" => ["viaire","uiaire","viaire"],
	"viande" => ["viande","uiande"],
	"vie" => ["vie","uie","vie"],
	"vierge" => ["vierge","uierge","uirge","vierge","virge","virginité"],
	"vieil" => ["vieil","uielle","uiellece","vieillece","vieses"],
	"vilain" => ["vilain","uilai","uilain","uilaine","uilaines","uilainnes","uilains","uile","uileine","uilonie","vilain","vilaine","vilaines","vilainne","vilainnes","vilains","vileine","vileines","vilenie","villain","villainez","villonie","vilonie"],
	"vile" => ["vile","uille","vile","ville"],
	"vin" => ["vin","uin","vin"],
	"violete" => ["violete","uioleite","uiolete","uioletes","violete"],
	"virelai" => ["virelai","uireli","uirelis","virelai","vireli","virelin","virellai","virellin","virenli","vrelai"],
	"visage" => ["visage","uis","uisage","vis","visage"],
	"vivre" => ["vivre","uescu","uit","uiuant","uiuerai","uiurai","uiure","uiuré","uiué","uivés","vit","viuant","viurai","viure","viuré","vivre"],
	"voer" => ["voer","uoee","veee"],
	"voie" => ["voie","uoie","voie"],
	"volenté" => ["volenté","uelenté","uolantei","uolanté","uolentei","uolenteis","uolenteit","uolenté","uoulentés","volenté","volentés","vollenté","voulentez"],
	"voloir" => ["voloir","ueil","ueill","ueul","ueult","ueut","uodroie","uoeil","uoil","uoill","uoille","uoldrez","uoleis","uolez","uoloie","uoloiei","uoloir","uolt","uolu","uolés","uot","uoudroie","uoudroiz","uoulez","uouloir","uueil","uueill","uueilliez","uuel","uuell","uuelt","uuet","uuil","vaudrez","vaudroie","vauroie","vaurés","veil","velt","veul","veulle","veult","veut","vodroie","voeil","voel","voiel","voil","volez","voliez","voloie","voloir","voloit","volra","volrai","volé","volés","voudrai","voudroie","voudroiz","vouldroie","voulez","vouloie","vouloir","vouroie","vueil","vueill","vueille","vueilliez","vuel","vuelt","vuet","vuil","vveil","weil","wel","welt","wil","woil"],
	"vrai" => ["vrai","uerai","ueraie","ueraiement","uoir","uoirement","urai","uraie","uraiement","urais","verai","veraie","vrai","vraie","vraiement","vraiment","vrais","vraiy","vrey"],
	"zo" => ["zo","zo"],
	"Aiglente" => ["Aiglente","aiglentine"],
	"Aigline" => ["Aigline","aigline"],
	"Aline" => ["Aline","alinette"],
	"Alixon" => ["Alixon","alixon","alizonnete"],
	"Amelot" => ["Amelot","amelot","ammelot","d'amelot","d'enmelot","emmelot"],
	"Aubert" => ["Aubert","aubert","aubiert"],
	"Aude" => ["Aude","aude"],
	"Baiart" => ["Baiart","baiars"],
	"Beatris" => ["Beatris","beatris","beatrix","beatriz","biatris","biatriz","biautrix","bietris","bietriz"],
	"Catherine" => ["Catherine","katerine"],
	"Charles" => ["Charles","charle"],
	"Clement" => ["Clement","climent"],
	"Doe" => ["Doe","doete"],
	"Doon" => ["Doon","doon"],
	"Eloi" => ["Eloi","eloi"],
	"Ernaut" => ["Ernaut","ernalt","ernault","ernaut"],
	"Fauvel" => ["Fauvel","fauuel"],
	"Garin" => ["Garin","garin"],
	"Gerart" => ["Gerart","gerars","gherars","gierars","girairs"],
	"Godefroi" => ["Godefroi","godefroi"],
	"Gui" => ["Gui","gioz","gui","guion","guiones","guionet","guionez","guiot","guioz","guis","guiz","quion"],
	"Henri" => ["Henri","henris"],
	"Hugues" => ["Hugues","huwes"],
	"Jeannette" => ["Jeannette","iohennete","jehannete"],
	"Isabelle" => ["Isabelle","izabelos","ysabelos","ysabelot"],
	"Joseph" => ["Joseph","joseph"],
	"Liegart" => ["Liegart","liegairt","liejart"],
	"Louis" => ["Louis","loouis"],
	"Mahalot" => ["Mahalot","mahalot"],
	"Margot" => ["Margot","marget","margot","margueron","marguet","mergot","mergrete"],
	"Mariette" => ["Mariette","mariete"],
	"Marion" => ["Marion","marion","marionete","marionnete","marions"],
	"Marot" => ["Marot","maroie","marot","marote","marotele"],
	"Mauberjon" => ["Mauberjon","mauberions"],
	"Nicolas" => ["Nicolas","nicholas"],
	"Perrin" => ["Perrin","perrin"],
	"Renaut" => ["Renaut","raynaut","regnault","regnaut","renaut"],
	"Robert" => ["Robert","robert","robeson","robesonnet","robeçonet","robeçonnet","robeçounet","robim","robin","robinet","robins","robinés"],
	"Thierry" => ["Thierry","thieris","tierri"],
	"Yolant" => ["Yolant","yolanz"],
	"Agien" => ["Agien","agien"],
	"Artois" => ["Artois","d'artois"],
	"Cleresvaus" => ["Cleresvaus","cleresuaus"],
	"Ermenion" => ["Ermenion","d'ermenion"],
	"France" => ["France","france"],
	"Gien" => ["Gien","gien"],
	"Jerusalem" => ["Jerusalem","jerusalem"],
	"Montjoie" => ["Montjoie","monioie"],
	"Montfort" => ["Montfort","monntfort","montfort "],
	"Normandie" => ["Normandie","normande"],
	"Piquigni" => ["Piquigni","pinquigni"],
	"Roiaumont" => ["Roiaumont","roiaumont"],
};

$c->{reading_text_words_map} = {};
foreach my $word (keys %{$c->{reading_text_words}})
{
	#add each key word to the hash
	push @{$c->{reading_text_words_map}->{normalize('C', $word)}}, normalize('C',$word);
	push @{$c->{reading_text_words_map}->{normalize('C', $word)}}, lc(normalize('C',$word)) if ($word ne lc($word)); #solve case issues
	foreach my $variation (@{$c->{reading_text_words}->{$word}})
	{
		#add each varient to the hash
		push @{$c->{reading_text_words_map}->{normalize('C', $variation)}}, normalize('C', $word);
	}
}


$c->{singer_blacklist} = [
"Aelis", "Amelot", "Anonyme", "Aucun (ajout du copiste)", "Aucun (citation)", "Belle Yolanz",
"Celui qui aura un cœur dévôt", "Ceux qui tardent à faire la volonté de leur dame", "Ceux qui verront la dame",
"Chantecler le coq", "Chaque âme", "David", "Des bergers", "Des bergers (st. III)",
"Des demoiselles se tenant par les mains", "Des inconnus", "Des jeunes gens et des jeunes filles",
"Des jeunes hommes à cheval, se tenant les mains deux par deux", "Deux barons", "Deux bergères (st. IV)",
"Deux compagnons", "Deux jeunes filles (st. I)", "Deux jeunes hommes", "Deux neveux du comte de Dinant",
"Dieu", "Emmelot", "Esther", "Garnier, l'ami de la bergère", "Gui", "Gui (st. I-II/IV)", "Guiot", "Imprécisé",
"Inconnu (le refrain est le premier vers d'un folio qui suit un folio manquant)", "L'amant", "L'amant potentiel",
"L'ami", "L'ami de Dieu", "L'ami de Marot (refrain final)", "L'amie du marié", "L'assemblée des danseurs",
"L'auteur", "L'auteur (st. I-IV)", "L'auteur (st. II)", "L'auteur (st. II/IV-VI)", "L'auteur (st. III/V)",
"L'auteur (st. V)", "L'auteur (st. VI)", "L'auteur et ses amis", "L'auteur et ses lecteurs", "L'auteur et une bergère",
"L'auteur et une compagne anonyme", "L'auteur ou l'ami de la dame", "L'auteur ou le copiste", "L'auteur-amoureux",
"L'auteur-héros", "L'auteure", "L'auteure (st. I)", "L'aînée des sœurs", "L'Église", "L'âme", "L'âme heureuse",
"L'âme égarée", "L'épouse", "La belle Aye", "La bergère (st. I)", "La chanson", "La compagnie", "La comtesse",
"La dame", "La dame (st. V)", "La fille d'en Hue", "La jeune fille qui lira l'œuvre", "La mère de la bergère (st. IV)",
"Le bon amoureux", "Le bon chanteur", "Le cœur amoureux", "Les acteurs du charivari", "Les amis du vilain",
"Les amoureux", "Les anges", "Les bons chanteurs", "Les compagnons de l'auteur", "Les cœurs amoureux", "Les dames",
"Les dames amoureuses depuis longtemps, découvrant un nouvel amour", "Les dames mariées", "Les demoiselles",
"Les femmes", "Les jouvenceaux", "Les jouvenceaux amoureux", "Les maris", "Les martyrs", "Les nonnes",
"Les sages jouvenceaux", "Les trompeurs", "Les vaillants amoureux", "Marot", "Marot (st. V)", "Marotele",
"Perrin (st. V)", "Phebus", "Son ami (st. IV)", "Un amoureux", "Un berger", "Un berger (Gui)", "Un berger (Robin)",
"Un chevalier", "Un jeune homme", "Un messager", "Un messager ?", "Un poète, cité par l'auteur",
"Un valet du comte de Spire", "Une belle", "Une bergère", "Une bergère (st. I)", "Une bergère (st. I-II)",
"Une bergère (st. I-IV)", "Une bergère (st. I/III/envoi)", "Une brunette", "Une dame", "Une dame (st. VI)",
"Une demoiselle", "Une des sœurs", "Une félonne", "Une jeune fille", "Une jeune fille (st. I-III)",
"Une jeune fille et son ami (st. V)", "Une jeune nonne", "Une voix", "« Celui qui cest refrait chanta »",
"« Celui qui chanta cest motet » (refrain-citation)", "« Cil qui dist »", "« Cui qui poit »", "« La belle »",
"« Le bon chanteur »", "« Les autres »", "« On » (refrain-citation)","« Celui qui chanta cest motet » (citation)",
"« Cil qui dist » (citation)","« On » (citation)", "« cius qui bien vos puist dire » (citation)"
];

$c->{singer_blacklist_hash} = {};
foreach my $word (@{$c->{singer_blacklist}})
{
	$c->{singer_blacklist_hash}->{normalize('C', $word)} = 1; 
}



$c->{generic_descriptor_blacklist} = [
"Refrain",
"Bestiaire","Chronique","Conte pieux","Correspondance","Débat strophique","Dit","Dit allégorique","Dit allégorique strophique","Dit strophique",
"Fabliau","Fatras","Miracle de la Vierge","Miracles illustrant les propriétés des choses","Motet farci?","Œuvre didactique","Poème allégorique",
"Poème en forme de débat","Poème épique","Poème narratif","Poème narratif strophique","Poème strophique","Probatio pennæ","Recueil de citations",
"Recueil de miracles de la Vierge","Recueil de proverbes","Rêverie","Sermon","Salut d'amour","Théâtre","Traduction-adaptation de l'Ars amatoria d'Ovide",
"Traduction-adaptation du cantique des Cantiques","Traité spirituel","Traité sur l'amour"
];

$c->{generic_descriptor_blacklist_hash} = {};
foreach my $word (@{$c->{generic_descriptor_blacklist}})
{
	$c->{generic_descriptor_blacklist_hash}->{lc(normalize('C', $word))} = 1; 
}

$c->{generic_descriptor_words} = 
{
	"Chanson" => ["Ballade avec des refrains","Ballade à refrain","Ballette avec des refrains","Ballette à refrain","Ballette à refrain et refrain interne","Chanson","Chanson avec des refrains","Chanson avec des refrains et refrain interne","Chanson balladée","Chanson balladée à refrain","Chanson d'aube à refrain","Chanson de mal mariée avec des refrains","Chanson de toile à refrain","Chanson à refrain","Chanson à refrain bilingue","Chanson à refrain et refrain interne","Chanson à refrain et refrains internes","Chanson à refrain interne","Descort","Estampie à refrain","Pastourelle","Pastourelle avec des refrains","Pastourelle avec des refrains et refrain interne","Pastourelle à refrain","Pastourelle à refrain et refrain interne","Pastourelle à refrain interne","Pastourelle à refrains internes","Reverdie à refrain","Rotruenge à refrain","Rotruenge à refrain interne","Serventois à refrain","Virelai"],
	"Clausula" => [],
	"Motet" => ["Motet","Motet enté","Motet-centon","Motet-refrain","Rondeau-motet", "Motet?"],
	"Organum" => [],
	"Rondeau" => ["Rondeau","Rondeau strophique","Rondet","Rondet strophique"],
	"Roman" => ["Roman","Roman allégorique","Roman d'aventures"],
};


$c->{generic_descriptor_words_map} = {};
foreach my $word (keys %{$c->{generic_descriptor_words}})
{
	#add each key word to the hash
	push @{$c->{generic_descriptor_words_map}->{lc(normalize('C', $word))}}, normalize('C',$word);
	foreach my $variation (@{$c->{generic_descriptor_words}->{$word}})
	{
		#add each varient to the hash
		push @{$c->{generic_descriptor_words_map}->{lc(normalize('C', $variation))}}, normalize('C', $word);
	}
}



$c->{circumstance_words} = {
	'Commentaires conclusifs' => [
		'Conclusion d\'une strophe',
		'Conclusion de la lettre',
		'Conclusion de la st. I',
		'Conclusion de la st. I (avertissement aux amoureux)',
		'Conclusion de la st. I (réponse à la proposition de mariage)',
		'Conclusion de la st. II',
		'Conclusion de la st. II (avertissement aux vilains)',
		'Conclusion de la st. II (réponse à la proposition de mariage)',
		'Conclusion de la st. III',
		'Conclusion de la st. III (l\'auteur est un vrai amant)',
		'Conclusion de la st. III (retour du vilain sur ses terres)',
		'Conclusion de la st. III (réponse à la proposition de mariage)',
		'Conclusion de la st. IV',
		'Conclusion de la st. IV (récit de l\'auteur)',
		'Conclusion de la st. IV (réponse à la proposition de mariage)',
		'Conclusion de la st. V',
		'Conclusion de la st. V (récit de l\'auteur)',
		'Conclusion de la st. V (réponse à la proposition de mariage)',
		'Conclusion de la st. VI',
		'Conclusion de la st. VI (récit de l\'auteur)',
		'Conclusion de la st. VI (réponse à la proposition de mariage)',
		'Conclusion de la st. VII',
		'Conclusion de la st. VII (récit de l\'auteur)',
		'Conclusion de la st. VII (réponse à la proposition de mariage)',
		'Conclusion de la st. VIII',
		'Conclusion de la st. VIII (arrivée du vilain)',
		'Conclusion de la st. VIII (récit de l\'auteur)',
		'Conclusion de la st. VIII (satisfaction d\'aimer)',
		'Conclusion de la st. IX',
		'Conclusion de la st. IX (arrivée du vilain)',
		'Conclusion de la st. IX (évocation des médisants)',
		'Conclusion de la st. X',
		'Conclusion de la st. X (arrivée du vilain)',
		'Conclusion de la st. X (évocation des médisants)',
		'Conclusion de la st. XI',
		'Conclusion de la st. XI (fin du récit de l\'auteur)',
		'Conclusion de la st. XII',
		'Conclusion de la st. XII (arrivée du vilain)',
		'Conclusion de la st. XII et du poème (envoi)',
		'Conclusion de la st. XIII',
		'Conclusion de la st. XIII (célébration du mariage)',
		'Conclusion de la st. XIV',
		'Conclusion de la st. XIV (célébration du mariage)',
		'Conclusion de la st. XV',
		'Conclusion de la st. XV (célébration du mariage)',
		'Conclusion de la st. XVI',
		'Conclusion de la st. XVI (célébration du mariage)',
		'Conclusion de la st. XVII',
		'Conclusion de la st. XVII (célébration du mariage)',
		'Conclusion de la st. XVIII',
		'Conclusion de la st. XVIII (arrivée de l\'ami de la châtelaine)',
		'Conclusion de la st. XIX',
		'Conclusion de la st. XIX (arrivée de l\'ami de la châtelaine)',
		'Conclusion de la st. XX',
		'Conclusion de la st. XX (arrivée de l\'ami de la châtelaine)',
		'Conclusion de la st. XXI',
		'Conclusion de la st. XXI (enlèvement de la châtelaine)',
		'Conclusion de la st. XXII',
		'Conclusion de la st. XXII (enlèvement de la châtelaine)',
		'Conclusion de la st. XXIII',
		'Conclusion de la st. XXIII (enlèvement de la châtelaine)',
		'Conclusion de la st. XXIV',
		'Conclusion de la st. XXV',
		'Conclusion de la st. XXV (enlèvement de la châtelaine)',
		'Conclusion de la st. XXVI',
		'Conclusion de la st. XXVI (enlèvement de la châtelaine)',
		'Conclusion de la st. XXVII',
		'Conclusion de la st. XXVII (enlèvement de la châtelaine)',
		'Conclusion de la st. XXVII et de la première partie du salut',
		'Conclusion de la st. XXVIII',
		'Conclusion de la st. XXVIII (enlèvement de la châtelaine)',
		'Conclusion de la st. XXIX',
		'Conclusion de la st. XXIX (retour du vilain sur ses terres)',
		'Conclusion de la st. XXX',
		'Conclusion de la st. XXX (retour du vilain sur ses terres)',
		'Conclusion de la st. XXXI',
		'Conclusion de la st. XXXII',
		'Conclusion de la st. XXXII (arrivée de la châtelaine sur les terres de son ami',
		'Conclusion de la st. XXXIII',
		'Conclusion de la st. XXXIII (arrivée de la châtelaine sur les terres de son ami)',
		'Conclusion de la st. XXXIV',
		'Conclusion de la st. XXXIV (départ de la châtelaine)',
		'Conclusion de la st. XXXV',
		'Conclusion de la st. XXXV (ultime commentaire de l\'histoire)',
		'Conclusion de la st. XXXVI',
		'Conclusion de la st. XXXVI (le clerc avoue être prêt à mourir par amour)',
		'Conclusion de la st. XXXVII',
		'Conclusion de la st. XXXVIII',
		'Conclusion de la st. XXXIX',
		'Conclusion de la st. XL',
		'Conclusion du bestiaire',
		'Conclusion du dit',
		'Conclusion du miracle',
		'Conclusion du poème (départ du verger d\'Amour)',
		'Conclusion du salut',
		'Fin de l\'œuvre',
		'Fin du prologue de l\'œuvre',
		'Fin du roman',
		'Après la conclusion du roman '
	],
	'Déplacements' => [
		'Arrivée au château de Chauvency après les joutes du lundi',
		'Arrivée aux joutes du jeudi après-midi',
		'Arrivée à la cour pour le mariage de Galeran',
		'Cortège dans la rue',
		'Cortège suivant la victoire de Gerart sur Galeran',
		'Dans les bois',
		'Déplacement à cheval',
		'En route vers la cour du roi',
		'En route vers le château d\'Harouge',
		'Entrée dans la salle du château du duc de Metz',
		'Entrée dans la ville de Metz',
		'Entrée à Maupertuis',
		'Entrée à Passe-Orgueil (fête finale)',
		'Marche dans la rue',
		'Voyage à Savernon',
		'À cheval',
		'À cheval dans la rue',
		'À cheval, en quittant le château des Illes Pertes',
		'Sortie du château de Chauvency pour assister aux joutes du jeudi après-midi',
		'Séparation après le tournoi, le vendredi',
		'Départ des fées',
		'Départ du poète',
		'Promenade dans le jardin',
		'Promenade dans le verger',
		'Retour au château de Chauvency après les joutes du jeudi après-midi',
		'Retour au château de Chauvency après les joutes du mardi',
		'Retour à Savernon '
	],
	'Illustrations de gloses' => ['Illustration de la glose finale du livre I sur la chasse amoureuse',
		'Illustration de la glose sur l\'impossibilité de servir deux maîtres à la fois',
		'Illustration de la glose sur l\'infidélité des hommes',
		'Illustration de la glose sur l\'intérêt des femmes pour la danse',
		'Illustration de la glose sur l\'orgueil',
		'Illustration de la glose sur l\'émotion engendrée par un beau son',
		'Illustration de la glose sur la bonne et la mauvaise renommées',
		'Illustration de la glose sur la désobéissance féminine',
		'Illustration de la glose sur la force d\'Hercule',
		'Illustration de la glose sur la jalousie',
		'Illustration de la glose sur la justification des actes blâmables',
		'Illustration de la glose sur la loyauté amoureuse',
		'Illustration de la glose sur la manière de danser les caroles',
		'Illustration de la glose sur la méfiance nécessaire envers les médisants',
		'Illustration de la glose sur la nécessité d\'être en paix pour être amoureux',
		'Illustration de la glose sur la nécessité de complimenter les femmes',
		'Illustration de la glose sur la nécessité de résister à l\'amour',
		'Illustration de la glose sur la nécessité des feintes amoureuses',
		'Illustration de la glose sur la nécessité des présents faits par amour',
		'Illustration de la glose sur la nécessité pour les femmes d\'êtres bien considérées par leurs maris',
		'Illustration de la glose sur la nécessité pour les hommes de pleurer devant les femmes pour les attendrir',
		'Illustration de la glose sur la nécessité, pour les hommes, de feindre la douleur',
		'Illustration de la glose sur la pitié des femmes',
		'Illustration de la glose sur la pérennité de l\'amour',
		'Illustration de la glose sur la responsabilité des maris dans le déshonneur de leurs femmes',
		'Illustration de la glose sur la retenue volontaire des hommes',
		'Illustration de la glose sur la résistance amoureuse des femmes',
		'Illustration de la glose sur la toute-puissance féminine',
		'Illustration de la glose sur la trahison des faux amis',
		'Illustration de la glose sur la trahison féminine',
		'Illustration de la glose sur la versatilité féminine',
		'Illustration de la glose sur la volonté des femmes à se faire désirer',
		'Illustration de la glose sur la volonté des femmes à être violentées',
		'Illustration de la glose sur le manque de courage de certains hommes',
		'Illustration de la glose sur le manque de courage des femmes',
		'Illustration de la glose sur les amoureux parjures',
		'Illustration de la glose sur les blessures de l\'amour',
		'Illustration de la glose sur les contreparties de l\'amour',
		'Illustration de la glose sur les disputes des couples mariés',
		'Illustration de la glose sur les diverses façons d\'assaillir les femmes en amour',
		'Illustration de la glose sur les démonstrations amoureuses ostentatoires',
		'Illustration de la glose sur les femmes dédaigneuses',
		'Illustration de la glose sur les jeux amoureux',
		'Illustration de la glose sur les mensonges d\'amour',
		'Illustration de la glose sur les obligations amoureuses',
		'Illustration de la glose sur les servitudes amoureuses',
		'Illustration de la glose sur les tournois comme preuve d\'amour',
		'Illustration de la glose sur les tromperies nécessaires',
		'Illustration de la nécessité de prier pour progresser dans l\'amour divin',
		'Illustre la présentation de l\'« amor sapiens »',
		'Illustre la présentation de l\'« amor fortis »',
		'Illustre la présentation de l\'« amor insatiabilis »',
		'Illustre la présentation de l\'« amor inseparabilis »',
		'Miracle de l\'enfant sauvé du feu dans son berveau',
		'Miracle de l\'ennemi qui s\'évanouit en entendant l\'Ave Maria',
		'Miracle de la conversion de sainte Catherine',
		'Miracle de la femme enceinte pendant trente mois enfantée par le nombril',
		'Miracle de saint Edmond',
		'Miracle des frères prêcheurs gardés par Marie sous son manteau',
		'Miracle des trois enfants qui levèrent des colonnes dans une église',
		'Miracle du moine dangereux',
		'Miracle du prêtre puni par saint Thomas '
	],
	'Requêtes' => [
		'Requête de Meliacin',
		'Requête de l\'auteur',
		'Requête de sa mère',
		'Requête de son père',
		'Requête des suivantes de Celinde '],
	'Scènes de repas' => [
		'Banquet',
		'Banquet offert par Renart à Passe-Orgueil (premier mets)',
		'Banquet offert par Renart à Passe-Orgueil (deuxième mets)',
		'Banquet offert par Renart à Passe-Orgueil (troisième mets)',
		'Début du banquet final à Passe-Orgueil',
		'Fin du pique-nique',
		'Pique-nique',
		'Préparation du pique-nique '],
	'Scènes festives' => ['Après le dîner au château de Chauvency suivant les joutes du lundi',
		'Après le dîner au château de Chauvency suivant les joutes du mardi',
		'Après le jeu du chapelet',
		'Après le repas',
		'Après un repas (premier soir de la table ronde de Machaut)',
		'Avant le tournoi de Fere',
		'Avant les jeux',
		'Bal de la Toussaint au Paradis',
		'Dans la salle du château de Nevers',
		'Début de la fête de la réconciliation à Maupertuis',
		'Fête après un repas',
		'Fête de la réconciliation à Maupertuis (avant le dîner)',
		'Fête des Amoureux lors du siège du château d\'Amour occupé par Envie',
		'Fête du paon',
		'Fêtes de mai à Mayence',
		'Huitième joute du mardi',
		'Jeu du chapelet',
		'Neuvième joute du mardi',
		'Signature de la paix entre Noble et Renart',
		'Soirée suivant les joutes',
		'Tournoi (deuxième jour de la table ronde de Machaut)',
		'Troisième joute du mardi '],
	'Scènes intimes' => [
		'Conversation',
		'Dans la chambre d\'Aiglente',
		'Le matin, en entendant une alouette',
		'Lecture des lettres d\'amour de Renart',
		'Travaux d\'aiguille',
		'À sa fenêtre '],
	'Divers' => [
		'Accueil de Rousseau à Maupertuis',
		'Accueilli par Noble',
		'Affirme sa volonté de servir Dieu',
		'Anxieuse d\'être accompagnée par Dieu',
		'Apostrophe initiale de l\'auteur à la dame',
		'Après avoir bu le philtre d\'amour',
		'Après avoir envoyé son message à l\'auteur-amoureux',
		'Après avoir quitté sa dame',
		'Après avoir retrouvé la grâce',
		'Après avoir reçu le message de sa dame',
		'Après avoir reçu le rossignol, messager de sa dame',
		'Après l\'accomplissement de son amour, l\'auteur pourra chanter',
		'Après l\'envoi du rossignol à son ami',
		'Après la complainte de l\'ermite',
		'Après la messe du jeudi à Chauvency',
		'Après la prière au dieu d\'Amour',
		'Après la prière à la dame',
		'Après le don du cœur de la dame à l\'auteur-amoureux',
		'Après le jugement de Dieu',
		'Après s\'être adressée à Dieu',
		'Après sa mort',
		'Au moment de la crucifixion',
		'Au purgatoire, en attente du paradis',
		'Avant la préparation du philtre d\'amour',
		'Avec Anceau de Bries, une nuit durant le siège de la Candare',
		'Chasse d\'Amour',
		'Commentaire sur le mariage au Christ',
		'Commentaire sur les mal mariées',
		'Condamnation de la guerre',
		'Conseil de l\'auteur (Miracle du frère prêcheur visité par Marie sur son lit de mort)',
		'Conseil de saint Augustin',
		'Des amis intercèderont pour lui auprès de sa dame',
		'Description de la dame',
		'Description de la prison d\'amour',
		'Description de ses tourments amoureux',
		'Description des maux d\'amour',
		'Description du bois de Jonece',
		'Dialogue entre l\'auteur et sa dame',
		'Difficulté de séduire Fortune',
		'Discours sur le mariage',
		'Don du cœur de l\'auteur-amoureux',
		'Début de la pièce',
		'Début du songe',
		'Dépossédé de ses terres et en souvenir de son amie',
		'Exhortation à revenir vers Dieu',
		'Elle attend Cleomadés',
		'Elle attend Meliacin',
		'Elle attend la venue du sauveur',
		'Elle attend son amant, le roi Noble',
		'Elle chevauche Aristote',
		'Elle dote l\'homme parfait de la liberté de l\'âme',
		'Enlèvement de Marion par le chevalier',
		'Enlèvement de la bergère',
		'Envoi d\'un messager à la recherche de Gerart',
		'Envoi du message de la dame à l\'auteur-amoureux',
		'Exergue au salut',
		'Exergue au sermon',
		'Exposition de ses maux',
		'Fabrication du char de Prudence',
		'Il transforme son amour terrestre en amour divin',
		'Introduction de l\'œuvre',
		'L\'amant est assailli de serpents s\'il échoue à accéder à la roue de Fortune',
		'L\'auteur a réussi son ascension de la tour d\'amour',
		'L\'auteur a trouvé la force en écrivant son dit',
		'L\'auteur affirme sa volonté de servir Dieu',
		'L\'auteur décide de servir sa dame',
		'L\'auteur est relégué dans la fosse de la tour d\'amour',
		'L\'auteur implore la dame de le laisser accéder à la tour d\'amour',
		'L\'auteur implore sa dame de le prendre en pitié',
		'L\'auteur implore sa dame de le secourir',
		'L\'auteur ne peut entrer dans la tour d\'amour faute d\'être aimé par sa dame',
		'L\'auteur prévient la dame qu\'il a entendu chanter son amant',
		'L\'auteur s\'adresse à la dame',
		'La châtelaine n\'est pas venue au rendez-vous fixé',
		'La dame donne congé au poète',
		'La dame décide quand l\'amant pourra sortir de la prison d\'amour',
		'La dame espère le retour de son ami',
		'La dame s\'aperçoit de la perte de son amour',
		'La porte de la tour est l\'espérance d\'amour',
		'Le dit n\'est pas destiné aux vilains',
		'Le mariage permet de sortir de la prison d\'amour',
		'Les deux ennemis ont décidé une trêve',
		'Les yeux sont une des voies d\'accès à la tour d\'amour',
		'Lors de leur expulsion de l\'auberge',
		'Nomination de l\'abbesse (Débonaireté)',
		'Nomination de l\'hôtelière (Charité)',
		'Nomination de l\'infirmière (Pitié)',
		'Nomination de l\'inspectrice (Doux Regard)',
		'Nomination de la boursière (Miséricorde)',
		'Nomination de la cellerière (Pourvoyance)',
		'Nomination de la chantre (Joliveté)',
		'Nomination de la chapelaine (Esperance)',
		'Nomination de la directrice du réfectoire (Vigueur)',
		'Nomination de la prieure (Miséricorde)',
		'Nomination de la sacristaine (Raison)',
		'Nomination de la sous chantre (Renvoiseüre)',
		'Nomination de la sous prieure (Tempérance)',
		'Nomination de la sous-cellerière (Largesse)',
		'Nomination de la vestiaire (Courtoisie)',
		'Nécessité d\'enchanter les ennemis',
		'Perte de la nef de Noble',
		'Point de départ de la description de la prison d\'amour',
		'Prisonnière du sorcier Clamazart',
		'Prière',
		'Prière à la dame',
		'Précède le don du cœur de la dame à l\'auteur-amoureux',
		'Présentation publique d\'Euriaut',
		'Quête de Celinde',
		'Rappel de la citation précédente du même refrain',
		'Rappel de la passion du Christ',
		'Rappel de son incarnation',
		'Rencontre de la dame',
		'Référence au début du livre lui-même',
		'Réponse au rondeau chanté par sa dame )',
		'Réponse au rondeau chanté par sa dame',
		'Réponse à la prière de l\'auteur',
		'Réveil du songe',
		'S\'abandonne au bon vouloir de sa dame',
		'Seconde rencontre entre l\'auteur et sa dame',
		'Seconde tentative de séduction du chevalier',
		'Siège de l\'auteur-amoureux',
		'Songe de l\'auteur',
		'Suite du rondeau initial',
		'Sur le point de mourir',
		'Tentative de séduction',
		'Tentative de séduction du chevalier',
		'À l\'auberge',
		'À la vue de sa dame',
		'À propos du pardon',
		'Éloge de la dame',
		'Évocation d\'Adam de la Halle',
		'Évocation de Fortune, qui assure la communication entre les étages de la tour d\'amour',
		'Évocation de l\'arbre de vie',
		'Évocation de la dame',
		'Évocation de la possibilité d\'aimer ailleurs',
		'Évocation de la sortie de la prison d\'amour',
		'Évocation des acteurs de la roue de Fortune (Amoureuse souffrance)',
		'Évocation des acteurs de la roue de Fortune (Courtoisie)',
		'Évocation du dit',
		'Évocation du jardin du Paradis '
	],
};

$c->{circumstance_map} = {};
foreach my $word (keys %{$c->{circumstance_words}})
{
	#add each key word to the hash
	push @{$c->{circumstance_map}->{lc(normalize('C', $word))}}, normalize('C',$word);
	foreach my $variation (@{$c->{circumstance_words}->{$word}})
	{
		#add each varient to the hash
		push @{$c->{circumstance_map}->{lc(normalize('C', $variation))}}, normalize('C', $word);
	}
}

